PathWyse: Label Class Reference
Label Class Reference
#include <label.h>
Public Member Functions
Label ()
Label (const Label &obj)
virtual ~Label ()=default
void initLabel (int node, Label *predecessor, bool direction, int n_res)
void updateLabel (int node, Label *predecessor)
int getObjective ()
void setObjective (int objective)
int getSnapshot (int resID)
std::vector< int > & getSnapshot ()
void setSnapshot (int resID, int value)
void setSnapshot (std::vector< int > snapshot)
int getNode ()
bool getDirection ()
Label * getPredecessor ()
int getPredecessorNode ()
bool isValid ()
void operator= (const Label &obj)
bool operator== (const Label &obj)
bool operator!= (const Label &obj)
void printLabel ()
void printPredecessors ()
Protected Attributes
int node
bool direction
Label * predecessor
int objective
std::vector< int > snapshot
Detailed Description
Definition at line 7 of file label.h.
Constructor & Destructor Documentation
Label() [1/2]
Label::Label () inline
Label management
Definition at line 13 of file label.h.
{objective = UNKNOWN;}
Label() [2/2]
Label::Label (const Label & obj)
Label management
Definition at line 5 of file label.cpp.
{
    node = obj.node;
    direction = obj.direction;
    predecessor = obj.predecessor;
    objective = obj.objective;
    snapshot = obj.snapshot;
}
~Label()
virtual Label::~Label () virtual default
Member Function Documentation
initLabel()
void Label::initLabel (int node, Label * predecessor, bool direction, int n_res)
Definition at line 14 of file label.cpp.
{
    this->node = node;
    this->predecessor = predecessor;
    this->direction = direction;
    this->snapshot.resize(n_res, 0);
}
Referenced by LMacyclic::buildTour(), LMDefault::buildTour(), Dijkstra::buildTour(), LMacyclic::initLM(), LMDefault::initLM(), and Dijkstra::solve().
updateLabel()
void Label::updateLabel (int node, Label * predecessor)
Definition at line 21 of file label.cpp.
{
    this->node = node;
    this->predecessor = predecessor;
}
Referenced by LMacyclic::extendLabel(), Dijkstra::extendLabel(), Dijkstra::solve(), and LabelAdv::updateLabel().
getObjective()
int Label::getObjective () inline
Definition at line 23 of file label.h.
{return objective;}
Referenced by Dijkstra::checkFeasibility(), LMDefault::classicJoin(), LMDefault::dominates(), LMacyclic::earlyUpdate(), LMacyclic::extendLabel(), Dijkstra::extendLabel(), LMDefault::extendLabel(), LMDefault::findLabels(), Dijkstra::getDistance(), LMDefault::getSolutionLabels(), Preprocessing::getSplit(), LMacyclic::initLM(), LMacyclic::insert(), LMDefault::insert(), LMacyclic::join(), Dijkstra::joinCompletion(), Dijkstra::joinLabels(), LMDefault::naiveJoin(), LMDefault::orderedJoin(), and Dijkstra::solve().
setObjective()
void Label::setObjective (int objective) inline
Definition at line 24 of file label.h.
{this->objective = objective;}
Referenced by LMacyclic::buildTour(), LMDefault::buildTour(), Dijkstra::buildTour(), LMacyclic::extendLabel(), Dijkstra::extendLabel(), LMDefault::extendLabel(), LMacyclic::initLM(), and Dijkstra::solve().
getSnapshot() [1/2]
int Label::getSnapshot (int resID) inline
Definition at line 26 of file label.h.
{return snapshot[resID];}
Referenced by LMDefault::dominates(), LMacyclic::earlyUpdate(), LMacyclic::extendLabel(), Dijkstra::extendLabel(), LMDefault::extendLabel(), LMDefault::findLabels(), Dijkstra::getDistance(), LMacyclic::insert(), LMDefault::insert(), LMDefault::isCriticalExtensionFeasible(), Dijkstra::isCriticalLabelValid(), LMacyclic::isDominated(), LMacyclic::isExtensionFeasible(), LMDefault::isExtensionFeasible(), LMDefault::isJoinFeasible(), LMacyclic::join(), Dijkstra::joinLabels(), and Dijkstra::solve().
getSnapshot() [2/2]
std::vector< int > & Label::getSnapshot () inline
Definition at line 27 of file label.h.
{return snapshot;}
setSnapshot() [1/2]
void Label::setSnapshot (int resID, int value) inline
Definition at line 28 of file label.h.
{snapshot[resID] = value;}
Referenced by LMacyclic::buildTour(), LMDefault::buildTour(), Dijkstra::buildTour(), LMacyclic::extendLabel(), Dijkstra::extendLabel(), LMDefault::extendLabel(), LMacyclic::initLM(), and Dijkstra::solve().
setSnapshot() [2/2]
void Label::setSnapshot (std::vector< int > snapshot) inline
Definition at line 29 of file label.h.
{this->snapshot = snapshot;}
getNode()
int Label::getNode () inline
Queries
Definition at line 32 of file label.h.
{return node;}
Referenced by Algorithm::buildPath(), LMacyclic::closeLabel(), LMacyclic::earlyUpdate(), PWAcyclic::extend(), PWDefault::extend(), LMacyclic::extendLabel(), Dijkstra::extendLabel(), LMDefault::extendLabel(), LMDefault::findLabels(), LMDefault::getCandidateNode(), getPredecessorNode(), LMacyclic::insert(), LMDefault::insert(), LMDefault::isCriticalExtensionFeasible(), Dijkstra::isCriticalLabelValid(), LMacyclic::isDominated(), LMacyclic::isExtensionFeasible(), LMDefault::isExtensionFeasible(), LMDefault::isJoinFeasible(), Dijkstra::isLabelValid(), LMacyclic::join(), Dijkstra::joinCompletion(), Dijkstra::joinLabels(), printLabel(), Dijkstra::solve(), and LMDefault::updateUnreachables().
getDirection()
bool Label::getDirection () inline
Definition at line 33 of file label.h.
{return direction;}
Referenced by LMacyclic::closeLabel(), LMacyclic::earlyUpdate(), PWAcyclic::extend(), PWDefault::extend(), LMacyclic::extendLabel(), LMDefault::extendLabel(), LMDefault::getCandidate(), LMDefault::getSolutionLabels(), LMacyclic::insert(), LMDefault::insert(), LMDefault::isCriticalExtensionFeasible(), Dijkstra::isCriticalLabelValid(), LMacyclic::isDominated(), LMacyclic::isExtensionFeasible(), LMDefault::isExtensionFeasible(), Dijkstra::isLabelValid(), LMacyclic::join(), Dijkstra::joinCompletion(), PWDefault::labeling(), PWAcyclic::solve(), and LMDefault::updateUnreachables().
getPredecessor()
Label * Label::getPredecessor () inline
Definition at line 34 of file label.h.
{return predecessor;}
Referenced by Algorithm::buildPath(), PWDefault::extend(), Dijkstra::managePaths(), and printPredecessors().
getPredecessorNode()
int Label::getPredecessorNode () inline
Definition at line 35 of file label.h.
{return predecessor ? predecessor->getNode() : -1;}
Referenced by LMDefault::dominates(), LMDefault::isJoinFeasible(), and LMDefault::updateUnreachables().
isValid()
bool Label::isValid () inline
Definition at line 37 of file label.h.
{return objective != UNKNOWN;}
Referenced by LMacyclic::join().
operator=()
void Label::operator= (const Label & obj)
Operators
Definition at line 27 of file label.cpp.
{
    if(this == &obj) return;
    node = obj.node;
    direction = obj.direction;
    predecessor = obj.predecessor;
    objective = obj.objective;
    snapshot = obj.snapshot;
}
Referenced by LabelAdv::operator=().
operator==()
bool Label::operator== (const Label & obj)
Definition at line 37 of file label.cpp.
{
    if(node != obj.node or direction != obj.direction or objective != obj.objective or snapshot != obj.snapshot)
        return false;
    return true;
}
Referenced by LabelAdv::operator==().
operator!=()
bool Label::operator!= (const Label & obj)
Definition at line 44 of file label.cpp.
{
    if (node != obj.node or direction != obj.direction or objective != obj.objective or snapshot != obj.snapshot)
        return true;
    return false;
}
Referenced by LabelAdv::operator!=().
printLabel()
void Label::printLabel ()
Output management
Definition at line 52 of file label.cpp.
                       {
    if(Parameters::getVerbosity() < 0)
        return;
    std::cout<<"------------"<<std::endl;
    std::cout<<"Node: "<< node << std::endl;
    if(predecessor)
        std::cout<<"Predecessor: "<< predecessor->getNode() << std::endl;
    std::cout<<"Direction: " << direction << std::endl;
    std::cout<<"Objective: " << objective << std::endl;
    std::cout<<"Resource snapshot: " << std::endl;
    for(auto& s: snapshot)
        std::cout << s << " "  << std::endl;
    std::cout<<"------------"<<std::endl;
}
Referenced by LMDefault::printCandidates(), LMDefault::printClosed(), and printPredecessors().
printPredecessors()
void Label::printPredecessors ()
Definition at line 68 of file label.cpp.
{
    if(getPredecessor())
        getPredecessor()->printPredecessors();
    printLabel();
}
Referenced by printPredecessors().
Member Data Documentation
node
int Label::node protected
Definition at line 50 of file label.h.
Referenced by getNode(), initLabel(), LabelAdv::initVisited(), LabelAdv::isReachable(), Label(), operator!=(), operator=(), operator==(), printLabel(), LabelAdv::setUnreachable(), updateLabel(), and LabelAdv::updateLabel().
direction
bool Label::direction protected
Definition at line 51 of file label.h.
Referenced by getDirection(), initLabel(), Label(), operator!=(), operator=(), operator==(), and printLabel().
predecessor
Label* Label::predecessor protected
Definition at line 52 of file label.h.
Referenced by getPredecessor(), getPredecessorNode(), initLabel(), Label(), operator=(), printLabel(), updateLabel(), and LabelAdv::updateLabel().
objective
int Label::objective protected
Definition at line 55 of file label.h.
Referenced by getObjective(), isValid(), Label(), Label(), operator!=(), operator=(), operator==(), printLabel(), and setObjective().
snapshot
std::vector<int> Label::snapshot protected
Definition at line 56 of file label.h.
Referenced by getSnapshot(), getSnapshot(), initLabel(), Label(), operator!=(), operator=(), operator==(), printLabel(), setSnapshot(), and setSnapshot().
The documentation for this class was generated from the following files:
label.h
label.cpp