PathWyse: Resource Class Reference
Resource Class Reference abstract
#include <resource.h>
Public Member Functions
Resource ()
virtual ~Resource ()
void setName (std::string name)
std::string getName ()
int getInitValue ()
void setInitValue (int init_value)
void increaseInitValue (int delta)
void multiplyInitValue (float factor)
void setBounds (int lower_bound, int upper_bound)
void setLB (int lower_bound)
void setUB (int upper_bound)
void increaseUB (int delta)
void increaseLB (int delta)
void multiplyUB (float factor)
void multiplyLB (float factor)
int getLB ()
int getUB ()
void setNodeBounds (std::vector< int > node_lower_bound, std::vector< int > node_upper_bound)
void setNodeBound (int n_nodes, int i, int node_lower_bound, int node_upper_bound)
void increaseNodeBound (int i, int delta)
void multiplyNodeBound (int i, float factor)
int getNodeLB (int node)
int getNodeUB (int node)
std::vector< int > & getNodesLB ()
std::vector< int > & getNodesUB ()
void scaleResource (float scaling)
void initData (bool compress_data=false, int n_nodes=1)
void setData (ResourceData *data)
ResourceData * getData ()
int getArcCost (int i, int j)
void setArcCost (int i, int j, int cost)
void increaseArcCost (int i, int j, int delta)
void multiplyArcCost (int i, int j, float factor)
int getNodeCost (int i)
void setNodeCost (int i, int cost)
void setNodeCosts (std::vector< int > costs)
void increaseNodeCost (int i, int delta)
void multiplyNodeCost (int i, float factor)
virtual void init (int origin, int destination)
virtual int extend (int current_value, int i, int j, bool direction=true)=0
virtual int join (int current_value_forward, int current_value_backward, int i, int j)=0
virtual int join (int current_value_forward, int current_value_backward, int node)=0
virtual bool isFeasible (int current_value, int current_node=-1, double bounding=1, bool direction=true)=0
Protected Attributes
std::string name
int init_value
int lower_bound
int upper_bound
std::vector< int > node_lower_bound
std::vector< int > node_upper_bound
ResourceData * data
Detailed Description
Definition at line 8 of file resource.h.
Constructor & Destructor Documentation
Resource()
Resource::Resource () inline
Resource management
Definition at line 14 of file resource.h.
               {
        init_value = 0;
        lower_bound = INFMINUS;
        upper_bound = INFPLUS;
    };
~Resource()
virtual Resource::~Resource () inline virtual
Definition at line 20 of file resource.h.
{delete data;}
Member Function Documentation
setName()
void Resource::setName (std::string name) inline
Definition at line 23 of file resource.h.
{this->name = name;}
getName()
std::string Resource::getName () inline
Definition at line 24 of file resource.h.
{return name;}
Referenced by LMDefault::printStepConsumption().
getInitValue()
int Resource::getInitValue () inline
Definition at line 27 of file resource.h.
{return init_value;}
Referenced by LMacyclic::buildTour(), LMDefault::buildTour(), Dijkstra::buildTour(), LMacyclic::initLM(), and Dijkstra::solve().
setInitValue()
void Resource::setInitValue (int init_value) inline
Definition at line 28 of file resource.h.
{this->init_value = init_value;}
Referenced by Solver::setInitCost().
increaseInitValue()
void Resource::increaseInitValue (int delta) inline
Definition at line 29 of file resource.h.
{init_value += delta;}
multiplyInitValue()
void Resource::multiplyInitValue (float factor) inline
Definition at line 30 of file resource.h.
{init_value *= factor;}
Referenced by Problem::scaleAllData(), and scaleResource().
setBounds()
void Resource::setBounds (int lower_bound, int upper_bound) inline
Bounds
Definition at line 34 of file resource.h.
{this->lower_bound = lower_bound; this->upper_bound = upper_bound;}
setLB()
void Resource::setLB (int lower_bound) inline
Definition at line 35 of file resource.h.
{this->lower_bound = lower_bound;}
setUB()
void Resource::setUB (int upper_bound) inline
Definition at line 36 of file resource.h.
{this->upper_bound = upper_bound;}
increaseUB()
void Resource::increaseUB (int delta) inline
Definition at line 37 of file resource.h.
{upper_bound += delta;}
increaseLB()
void Resource::increaseLB (int delta) inline
Definition at line 38 of file resource.h.
{lower_bound += delta;}
multiplyUB()
void Resource::multiplyUB (float factor) inline
Definition at line 39 of file resource.h.
{upper_bound *= factor;}
Referenced by Problem::scaleAllData(), and scaleResource().
multiplyLB()
void Resource::multiplyLB (float factor) inline
Definition at line 40 of file resource.h.
{lower_bound *= factor;}
Referenced by Problem::scaleAllData(), and scaleResource().
getLB()
int Resource::getLB () inline
Definition at line 41 of file resource.h.
{return lower_bound;}
getUB()
int Resource::getUB () inline
Definition at line 42 of file resource.h.
{return upper_bound;}
setNodeBounds()
void Resource::setNodeBounds (std::vector< int > node_lower_bound, std::vector< int > node_upper_bound) inline
Definition at line 45 of file resource.h.
{
        this->node_lower_bound = node_lower_bound;
        this->node_upper_bound = node_upper_bound;
    }
setNodeBound()
void Resource::setNodeBound (int n_nodes, int i, int node_lower_bound, int node_upper_bound) inline
Definition at line 50 of file resource.h.
{
        if(this->node_lower_bound.empty())
            this->node_lower_bound.resize(n_nodes, 0);
        if(this->node_upper_bound.empty())
            this->node_upper_bound.resize(n_nodes, 0);
        this->node_lower_bound[i] = node_lower_bound;
        this->node_upper_bound[i] = node_upper_bound;
    }
increaseNodeBound()
void Resource::increaseNodeBound (int i, int delta) inline
Definition at line 60 of file resource.h.
{
        if(not node_lower_bound.empty())
            node_lower_bound[i] += delta;
        if(not node_upper_bound.empty())
            node_upper_bound[i] += delta;
    }
multiplyNodeBound()
void Resource::multiplyNodeBound (int i, float factor) inline
Definition at line 67 of file resource.h.
{
        if(not node_lower_bound.empty())
            node_lower_bound[i] *= factor;
        if(not node_upper_bound.empty())
            node_upper_bound[i] *= factor;
    }
Referenced by Problem::scaleAllData().
getNodeLB()
int Resource::getNodeLB (int node) inline
Definition at line 74 of file resource.h.
{return node_lower_bound[node];}
getNodeUB()
int Resource::getNodeUB (int node) inline
Definition at line 75 of file resource.h.
{return node_upper_bound[node];}
getNodesLB()
std::vector< int > & Resource::getNodesLB () inline
Definition at line 76 of file resource.h.
{return node_lower_bound;}
getNodesUB()
std::vector< int > & Resource::getNodesUB () inline
Definition at line 77 of file resource.h.
{return node_upper_bound;}
scaleResource()
void Resource::scaleResource (float scaling) inline
Scaling
Definition at line 80 of file resource.h.
{
        multiplyInitValue(scaling);
        multiplyUB(scaling);
        multiplyLB(scaling);
        for(int i = 0; i < node_lower_bound.size(); i++)
            multiplyNodeCost(i, scaling);
        data->scaleData(scaling);
    }
Referenced by Problem::scaleObjective().
initData()
void Resource::initData (bool compress_data = false, int n_nodes = 1) inline
Resource data structure management
Definition at line 92 of file resource.h.
{compress_data ? data = new ResourceDataMap(n_nodes): data = new ResourceDataMatrix(n_nodes);}
Referenced by Problem::addResource(), and Problem::initObjective().
setData()
void Resource::setData (ResourceData * data) inline
Definition at line 93 of file resource.h.
{this->data = data;}
getData()
ResourceData * Resource::getData () inline
Definition at line 94 of file resource.h.
{return data;}
getArcCost()
int Resource::getArcCost (int i, int j) inline
Definition at line 96 of file resource.h.
{return data->getArcCost(i,j);}
setArcCost()
void Resource::setArcCost (int i, int j, int cost) inline
Definition at line 97 of file resource.h.
{data->setArcCost(i,j, cost);}
Referenced by Problem::readProblem(), and Problem::readSparseProblem().
increaseArcCost()
void Resource::increaseArcCost (int i, int j, int delta) inline
Definition at line 98 of file resource.h.
{data->increaseArcCost(i, j, delta);}
multiplyArcCost()
void Resource::multiplyArcCost (int i, int j, float factor) inline
Definition at line 99 of file resource.h.
{data->multiplyArcCost(i, j, factor);}
Referenced by Problem::scaleAllData().
getNodeCost()
int Resource::getNodeCost (int i) inline
Definition at line 101 of file resource.h.
{return data->getNodeCost(i);}
Referenced by LMacyclic::buildTour(), LMDefault::buildTour(), Dijkstra::buildTour(), LMacyclic::initLM(), Solver::printNodeCosts(), and Dijkstra::solve().
setNodeCost()
void Resource::setNodeCost (int i, int cost) inline
Definition at line 102 of file resource.h.
{ data->setNodeCost(i, cost);}
Referenced by Problem::readProblem(), Problem::readSparseProblem(), and Solver::setNodeCost().
setNodeCosts()
void Resource::setNodeCosts (std::vector< int > costs) inline
Definition at line 103 of file resource.h.
{ data->setNodeCosts(costs);}
Referenced by Solver::setNodeCost().
increaseNodeCost()
void Resource::increaseNodeCost (int i, int delta) inline
Definition at line 104 of file resource.h.
{data->increaseNodeCost(i, delta);}
multiplyNodeCost()
void Resource::multiplyNodeCost (int i, float factor) inline
Definition at line 105 of file resource.h.
{data->multiplyNodeCost(i, factor);}
Referenced by Problem::scaleAllData(), and scaleResource().
init()
virtual void Resource::init (int origin, int destination) inline virtual
Resource behaviour definition
Reimplemented in TimeWindow.
Definition at line 109 of file resource.h.
{}
extend()
virtual int Resource::extend (int current_value, int i, int j, bool direction = true) pure virtual
Implemented in Capacity, DefaultCost, NodeLim, Time, and TimeWindow.
Referenced by LMacyclic::extendLabel(), Dijkstra::extendLabel(), and Dijkstra::solve().
join() [1/2]
virtual int Resource::join (int current_value_forward, int current_value_backward, int i, int j) pure virtual
Implemented in Capacity, DefaultCost, NodeLim, Time, and TimeWindow.
Referenced by LMacyclic::earlyUpdate(), LMacyclic::join(), and Dijkstra::joinLabels().
join() [2/2]
virtual int Resource::join (int current_value_forward, int current_value_backward, int node) pure virtual
Implemented in Capacity, DefaultCost, NodeLim, Time, and TimeWindow.
isFeasible()
virtual bool Resource::isFeasible (int current_value, int current_node = -1, double bounding = 1, bool direction = true) pure virtual
Implemented in Capacity, DefaultCost, NodeLim, Time, and TimeWindow.
Referenced by LMacyclic::earlyUpdate(), LMacyclic::insert(), Dijkstra::isCriticalLabelValid(), LMacyclic::isExtensionFeasible(), Dijkstra::isLabelValid(), LMacyclic::join(), and Dijkstra::joinLabels().
Member Data Documentation
name
std::string Resource::name protected
Definition at line 117 of file resource.h.
Referenced by Capacity::Capacity(), DefaultCost::DefaultCost(), getName(), NodeLim::NodeLim(), setName(), Time::Time(), and TimeWindow::TimeWindow().
init_value
int Resource::init_value protected
Definition at line 119 of file resource.h.
Referenced by Capacity::Capacity(), DefaultCost::DefaultCost(), getInitValue(), increaseInitValue(), multiplyInitValue(), NodeLim::NodeLim(), Resource(), setInitValue(), Time::Time(), and TimeWindow::TimeWindow().
lower_bound
int Resource::lower_bound protected
Definition at line 121 of file resource.h.
Referenced by getLB(), increaseLB(), multiplyLB(), Resource(), setBounds(), and setLB().
upper_bound
int Resource::upper_bound protected
Definition at line 121 of file resource.h.
Referenced by TimeWindow::extend(), getUB(), increaseUB(), TimeWindow::init(), Capacity::isFeasible(), DefaultCost::isFeasible(), NodeLim::isFeasible(), Time::isFeasible(), TimeWindow::isFeasible(), multiplyUB(), Resource(), setBounds(), and setUB().
node_lower_bound
std::vector<int> Resource::node_lower_bound protected
Definition at line 122 of file resource.h.
Referenced by TimeWindow::extend(), getNodeLB(), getNodesLB(), increaseNodeBound(), TimeWindow::isFeasible(), multiplyNodeBound(), scaleResource(), setNodeBound(), and setNodeBounds().
node_upper_bound
std::vector<int> Resource::node_upper_bound protected
Definition at line 122 of file resource.h.
Referenced by TimeWindow::extend(), getNodesUB(), getNodeUB(), increaseNodeBound(), TimeWindow::init(), TimeWindow::isFeasible(), multiplyNodeBound(), setNodeBound(), and setNodeBounds().
data
ResourceData* Resource::data protected
Definition at line 124 of file resource.h.
Referenced by Capacity::extend(), DefaultCost::extend(), Time::extend(), TimeWindow::extend(), getArcCost(), getData(), getNodeCost(), increaseArcCost(), increaseNodeCost(), TimeWindow::init(), initData(), TimeWindow::isFeasible(), DefaultCost::join(), Time::join(), TimeWindow::join(), Capacity::join(), DefaultCost::join(), Time::join(), TimeWindow::join(), multiplyArcCost(), multiplyNodeCost(), scaleResource(), setArcCost(), setData(), setNodeCost(), setNodeCosts(), and ~Resource().
The documentation for this class was generated from the following file:
resource.h