PathWyse: DataCollector Class Reference
DataCollector Class Reference
#include <data_collector.h>
Public Member Functions
DataCollector ()=default
DataCollector (std::string collection_name)
~DataCollector ()=default
void setCollectionName (std::string name)
void setOutputPath (std::string name)
int addDictionary (std::string &tag, int type)
int findIndex (std::string &tag, int type)
std::string getValue (std::string &tag)
std::string getDataStructure (std::string &tag)
void init (std::string tag, int value)
void init (std::string tag, std::string value)
void init (std::string tag, double value)
void initTime (std::string tag, double value=0)
void init (std::vector< std::string > tags, std::vector< int > values)
void init (std::vector< std::string > tags, std::vector< std::string > values)
void init (std::vector< std::string > tags, std::vector< double > values)
void initTimes (std::vector< std::string > &tags)
void collect (std::string tag, int value)
void collect (std::string tag, std::string value)
void collect (std::string tag, double value)
void collect (std::vector< std::string > tags, std::vector< int > values)
void collect (std::vector< std::string > tags, std::vector< std::string > values)
void collect (std::vector< std::string > tags, std::vector< double > values)
void increment (std::string tag, int value)
void increment (std::string tag, double value)
void startTime (std::string tag)
void stopTime (std::string tag)
void startGlobalTime ()
void stopGlobalTime ()
double getGlobalTime ()
double getGlobalTimeNow ()
void setHeader ()
void saveRecord ()
void writeData ()
void print ()
void print (std::vector< std::string > tags)
void reset (std::vector< std::string > tags)
void resetText (int id)
void resetTime (std::string tag, double value=0)
void resetTexts ()
void resetTimes (double value=0)
void resetTimesCumulative (double value=0)
void resetIntegers ()
void resetDecimals ()
void clearRecords ()
void clear ()
void setText (int id, std::string text)
std::string getText (int id)
void startTime (int id)
void stopTime (int id)
double getTime (int id)
double getTimeCumulative (int id)
void resetTime (int id)
void resetTimeCumulative (int id)
void setInteger (int id, int value)
void incrementInteger (int id, int value)
int getInt (int id)
void resetInteger (int id)
void setDecimal (int id, double value)
void incrementDecimal (int id, double value)
double getDecimal (int id)
void resetDecimal (int id)
Private Attributes
std::string name
std::string output_path
std::unordered_map< std::string, std::pair< int, int > > dict
std::vector< std::string > tag_text
std::vector< std::string > text
std::vector< double > times
std::vector< double > times_cumulative
std::vector< std::chrono::time_point< std::chrono::high_resolution_clock > > time_point
std::vector< std::string > tag_times
std::vector< int > integers
std::vector< std::string > tag_integers
std::vector< double > decimals
std::vector< std::string > tag_decimals
std::string header
std::list< std::string > records
Detailed Description
Definition at line 10 of file data_collector.h.
Constructor & Destructor Documentation
DataCollector() [1/2]
DataCollector::DataCollector () default
Data Collector Management
DataCollector() [2/2]
DataCollector::DataCollector (std::string collection_name) inline explicit
Definition at line 18 of file data_collector.h.
: name(collection_name) {setOutputPath(name);};
~DataCollector()
DataCollector::~DataCollector () default
Member Function Documentation
setCollectionName()
void DataCollector::setCollectionName (std::string name)
Data Collector Management
Definition at line 5 of file data_collector.cpp.
{
    this->name = name;
    setOutputPath(name);
}
Referenced by Algorithm::collectSolution(), PWAcyclic::initDataCollection(), PWDefault::initDataCollection(), Preprocessing::initDataCollection(), LMacyclic::setName(), and LMDefault::setName().
setOutputPath()
void DataCollector::setOutputPath (std::string name) inline
Definition at line 22 of file data_collector.h.
{output_path = Parameters::getCollectionPath() + name + ".csv";}
Referenced by DataCollector(), and setCollectionName().
addDictionary()
int DataCollector::addDictionary (std::string & tag, int type)
Definition at line 11 of file data_collector.cpp.
{
    int index = 0;
    switch(type) {
        case INTEGER:
            tag_integers.push_back(tag);
        integers.push_back(0);
        index = integers.size() - 1;
        break;
        case DECIMALS:
            tag_decimals.push_back(tag);
        decimals.push_back(0);
        index = decimals.size() - 1;
        break;
        case TIME:
            tag_times.push_back(tag);
        times.push_back(0);
        times_cumulative.push_back(0);
        time_point.push_back(std::chrono::high_resolution_clock::now());
        index = times.size() - 1;
        break;
        default:
            tag_text.push_back(tag);
        text.emplace_back("");
        index = text.size() - 1;
        break;
    }
    dict.insert({tag, std::make_pair(type, index)});
    return index;
}
Referenced by init(), init(), init(), and initTime().
findIndex()
int DataCollector::findIndex (std::string & tag, int type)
Definition at line 44 of file data_collector.cpp.
{
    int index = -1;
    if(Parameters::isCollecting()) {
        auto position = dict.find(tag);
        if(position != dict.end())
            index = position->second.second;
    }
    return index;
}
Referenced by collect(), collect(), collect(), increment(), increment(), resetTime(), startTime(), and stopTime().
getValue()
std::string DataCollector::getValue (std::string & tag)
Definition at line 55 of file data_collector.cpp.
{
    std::string value = "NULL";
    auto pos = dict.find(tag);
    if(pos != dict.end()) {
        int type = pos->second.first;
        int index = pos->second.second;
        switch(type) {
            case INTEGER:
                value = std::to_string(integers[index]);
            break;
            case DECIMALS:
                value = std::to_string(decimals[index]);
            break;
            case TIME:
                value = std::to_string(times[index]);
            break;
            default:
                value = text[index];
            break;
        }
    }
    return value;
}
getDataStructure()
std::string DataCollector::getDataStructure (std::string & tag)
Definition at line 82 of file data_collector.cpp.
{
    auto pos = dict.find(tag);
    if(pos != dict.end()) {
        int type = pos->second.first;
        switch(type) {
            case INTEGER:
                return "1) integer";
            case DECIMALS:
                return "2) decimal";
            case TIME:
                return "3) time";
            default:
                return "0) text";
        }
    }
    return "not found";
}
init() [1/6]
void DataCollector::init (std::string tag, int value)
Initialize collection of a value
Definition at line 112 of file data_collector.cpp.
{
    int index = addDictionary(tag, INTEGER);
    integers[index] = value;
}
Referenced by Problem::collectData(), init(), init(), init(), Algorithm::initDataCollection(), LMacyclic::initDataCollection(), PWAcyclic::initDataCollection(), LMDefault::initDataCollection(), PWDefault::initDataCollection(), Preprocessing::initDataCollection(), and Problem::initDataCollection().
init() [2/6]
void DataCollector::init (std::string tag, std::string value)
Initialize collection of a value
Definition at line 107 of file data_collector.cpp.
{
    int index = addDictionary(tag, TEXT);
    text[index] = std::move(value);
}
init() [3/6]
void DataCollector::init (std::string tag, double value)
Definition at line 117 of file data_collector.cpp.
{
    int index = addDictionary(tag, DECIMALS);
    decimals[index] = value;
}
initTime()
void DataCollector::initTime (std::string tag, double value = 0)
Definition at line 122 of file data_collector.cpp.
{
    int index = addDictionary(tag, TIME);
    times[index] = value;
    times_cumulative[index] = value;
}
Referenced by Algorithm::initDataCollection(), PWDefault::initDataCollection(), and initTimes().
init() [4/6]
void DataCollector::init (std::vector< std::string > tags, std::vector< int > values)
Definition at line 133 of file data_collector.cpp.
{
    for(int i = 0; i < tags.size(); i++)
        init(tags[i], values[i]);
}
init() [5/6]
void DataCollector::init (std::vector< std::string > tags, std::vector< std::string > values)
Definition at line 129 of file data_collector.cpp.
{
    for(int i = 0; i < tags.size(); i++)
        init(tags[i], values[i]);
}
init() [6/6]
void DataCollector::init (std::vector< std::string > tags, std::vector< double > values)
Definition at line 137 of file data_collector.cpp.
{
    for(int i = 0; i < tags.size(); i++)
        init(tags[i], values[i]);
}
initTimes()
void DataCollector::initTimes (std::vector< std::string > & tags)
Definition at line 142 of file data_collector.cpp.
{
    for(auto & t: tags)
        initTime(t);
}
collect() [1/6]
void DataCollector::collect (std::string tag, int value)
Collect and increment a value
Definition at line 156 of file data_collector.cpp.
{
    int index = findIndex(tag, INTEGER);
    if(index >= 0)
        integers[index] = value;
}
Referenced by collect(), collect(), collect(), LMacyclic::collectData(), PWAcyclic::collectData(), LMDefault::collectData(), PWDefault::collectData(), Preprocessing::collectData(), Problem::collectData(), Algorithm::collectSolution(), PWAcyclic::initDataCollection(), PWDefault::initDataCollection(), Preprocessing::initDataCollection(), Problem::readProblem(), Problem::readSparseProblem(), and LMDefault::update_split().
collect() [2/6]
void DataCollector::collect (std::string tag, std::string value)
Collect and increment a value
Definition at line 150 of file data_collector.cpp.
{
    int index = findIndex(tag, TEXT);
    if(index >= 0)
        text[index] = std::move(value);
}
collect() [3/6]
void DataCollector::collect (std::string tag, double value)
Definition at line 162 of file data_collector.cpp.
{
    int index = findIndex(tag, DECIMALS);
    if(index >= 0)
        decimals[index] = value;
}
collect() [4/6]
void DataCollector::collect (std::vector< std::string > tags, std::vector< int > values)
Definition at line 174 of file data_collector.cpp.
{
    for(int i = 0; i < tags.size(); i++)
        collect(tags[i], values[i]);
}
collect() [5/6]
void DataCollector::collect (std::vector< std::string > tags, std::vector< std::string > values)
Definition at line 169 of file data_collector.cpp.
{
    for(int i = 0; i < tags.size(); i++)
        collect(tags[i], values[i]);
}
collect() [6/6]
void DataCollector::collect (std::vector< std::string > tags, std::vector< double > values)
Definition at line 179 of file data_collector.cpp.
{
    for(int i = 0; i < tags.size(); i++)
        collect(tags[i], values[i]);
}
increment() [1/2]
void DataCollector::increment (std::string tag, int value)
Definition at line 185 of file data_collector.cpp.
{
    int index = findIndex(tag, INTEGER);
    if(index >= 0)
        integers[index] += value;
}
Referenced by Preprocessing::solveRound().
increment() [2/2]
void DataCollector::increment (std::string tag, double value)
Definition at line 191 of file data_collector.cpp.
{
    int index = findIndex(tag, DECIMALS);
    if(index >= 0)
        decimals[index] += value;
}
startTime() [1/2]
void DataCollector::startTime (std::string tag)
Time profile management
Time management
Definition at line 199 of file data_collector.cpp.
{
    int index = findIndex(tag, TIME);
    if(index >= 0)
        time_point[index] = std::chrono::high_resolution_clock::now();
}
Referenced by PWDefault::extend(), PWDefault::labeling(), and PWDefault::solve().
stopTime() [1/2]
void DataCollector::stopTime (std::string tag)
Definition at line 205 of file data_collector.cpp.
{
    int index = findIndex(tag, TIME);
    if(index >= 0) {
        double time = std::chrono::duration<double>(std::chrono::high_resolution_clock::now() - time_point[index]).count();
        times[index] += time;
        times_cumulative[index] += time;
    }
}
Referenced by PWDefault::extend(), PWDefault::labeling(), and PWDefault::solve().
startGlobalTime()
void DataCollector::startGlobalTime ()
Definition at line 214 of file data_collector.cpp.
{
    time_point[0] = std::chrono::high_resolution_clock::now();
}
Referenced by PWAcyclic::solve(), PWDefault::solve(), and Preprocessing::solveRound().
stopGlobalTime()
void DataCollector::stopGlobalTime ()
Definition at line 218 of file data_collector.cpp.
{
    double time = std::chrono::duration<double>(std::chrono::high_resolution_clock::now() - time_point[0]).count();
    times[0] += time;
    times_cumulative[0] += time;
}
Referenced by PWAcyclic::solve(), PWDefault::solve(), and Preprocessing::solveRound().
getGlobalTime()
double DataCollector::getGlobalTime () inline
Definition at line 66 of file data_collector.h.
{return times_cumulative[0];}
Referenced by Algorithm::getGlobalTime(), PWDefault::managePaths(), and print().
getGlobalTimeNow()
double DataCollector::getGlobalTimeNow ()
Definition at line 224 of file data_collector.cpp.
{
    double time = std::chrono::duration<double>(std::chrono::high_resolution_clock::now() - time_point[0]).count();
    return times_cumulative[0] + time;
}
setHeader()
void DataCollector::setHeader ()
Output management
Definition at line 233 of file data_collector.cpp.
{
    if(not Parameters::isOutputStored())
        return;
    header = "";
    for(auto & t: tag_text)
        header += t + ",";
    if(not tag_times.empty()) {
        header += tag_times[0] + ",global_time,";
        for(int i = 1; i < tag_times.size(); i++)
            header += tag_times[i] + "," + tag_times[i]  + "_cumulative,";
    }
    for(auto & t: tag_integers)
        header += t + ",";
    for(auto & t: tag_decimals)
        header += t + ",";
    //Manage and save header end
    if(header != "") {
        header.resize(header.size() - 1);
        header += "\n";
    }
}
Referenced by Problem::collectData(), Algorithm::initDataCollection(), LMacyclic::initDataCollection(), PWAcyclic::initDataCollection(), LMDefault::initDataCollection(), PWDefault::initDataCollection(), and Preprocessing::initDataCollection().
saveRecord()
void DataCollector::saveRecord ()
Definition at line 264 of file data_collector.cpp.
{
    if(not Parameters::isOutputStored())
        return;
    std::string r;
    for(auto & t: text)
        r += t + ",";
    for(int t = 0; t < times.size(); t++)
        r += std::to_string(times[t]) + "," + std::to_string(times_cumulative[t]) + ",";
    for(auto & i: integers)
        r += std::to_string(i) + ",";
    for(auto & d: decimals)
        r += std::to_string(d) + ",";
    //Manage and save record
    if(r != ""){
        r.resize(r.size() - 1);       //removes the last ","
        r += "\n";                       //adds endline
        records.push_back(r);
    }
}
Referenced by LMacyclic::collectData(), PWAcyclic::collectData(), LMDefault::collectData(), PWDefault::collectData(), Preprocessing::collectData(), Problem::collectData(), and Algorithm::collectSolution().
writeData()
void DataCollector::writeData ()
Definition at line 287 of file data_collector.cpp.
{
    if(not Parameters::isOutputStored() or records.empty())
        return;
    //Check if file already exists
    bool write_header = true;
    std::ifstream f_in(output_path.c_str());
    if(f_in.good()) write_header = false;
    f_in.close();
    //Save header and records to csv
    std::ofstream f;
    f.open(output_path.c_str(), std::ios_base::app);
    if(write_header) f << header;
    for (auto &r: records) f << r;
    f.close();
}
Referenced by PWAcyclic::collectData(), Problem::collectData(), Preprocessing::solve(), LMacyclic::writeData(), LMDefault::writeData(), and PWDefault::writeData().
print() [1/2]
void DataCollector::print ()
Definition at line 306 of file data_collector.cpp.
{
    if(not Parameters::isCollecting() or Parameters::getVerbosity() < 3)
        return;
    std::cout<<"-------Printing collection-------"<<std::endl;
    std::cout<<"Collection: " << name << std::endl;
    std::string line;
    for(int i = 0; i < tag_text.size(); i++){
        line = tag_text[i] + ": " + text[i];
        std::cout<<line<<std::endl;
    }
    for(int i = 0; i < tag_times.size(); i++){
        line = tag_times[i] + ": " + std::to_string(times[i]);
        std::cout<<line<<std::endl;
        if(i > 0)
            line = tag_times[i] + "_cumulative: " + std::to_string(times_cumulative[i]);
        else
            line = "Global_time: " + std::to_string(times_cumulative[i]);
        std::cout<<line<<std::endl;
    }
    for(int i = 0; i < tag_integers.size(); i++){
        line = tag_integers[i] + ": " + std::to_string(integers[i]);
        std::cout<<line<<std::endl;
    }
    for(int i = 0; i < tag_decimals.size(); i++){
        line = tag_decimals[i] + ": " + std::to_string(decimals[i]);
        std::cout<<line<<std::endl;
    }
    std::cout<<"--------------------"<<std::endl;
}
Referenced by PWDefault::solve().
print() [2/2]
void DataCollector::print (std::vector< std::string > tags)
Definition at line 342 of file data_collector.cpp.
{
    if(not Parameters::isCollecting() or Parameters::getVerbosity() < 0)
        return;
    std::string value;
    int type;
    for(auto & t: tags) {
        if(t == "Global_time") {
            std::cout<<"Global_time: " << getGlobalTime() <<std::endl;
            continue;
        }
        std::cout<<t + ": ";
        auto pos = dict.find(t);
        if(pos != dict.end()) {
            int type = pos->second.first;
            int index = pos->second.second;
            switch(type) {
                case INTEGER:
                    std::cout<<getInt(index);
                    break;
                case DECIMALS:
                    std::cout<<getDecimal(index);
                    break;
                case TIME:
                    std::cout<<getTime(index)<<std::endl;
                    std::cout<<t + "_cumulative: " << getTimeCumulative(index);
                    break;
                default:
                    std::cout<<getText(index);
                    break;
            }
        }
        std::cout<<std::endl;
    }
}
reset()
void DataCollector::reset (std::vector< std::string > tags)
Reset values and clear data structures
Definition at line 387 of file data_collector.cpp.
{
    if(not Parameters::isCollecting())
        return;
    for(auto & tag: tags) {
        auto pos = dict.find(tag);
        if(pos != dict.end()) {
            int type = pos->second.first;
            int index = pos->second.second;
            switch(type) {
                case INTEGER:
                    resetInteger(index);
                    break;
                case DECIMALS:
                    resetDecimal(index);
                    break;
                case TIME:
                    resetTime(index);
                    break;
                default:
                    resetText(index);
                    break;
            }
        }
    }
}
resetText()
void DataCollector::resetText (int id) inline
Definition at line 79 of file data_collector.h.
{text[id] = "";}
Referenced by reset().
resetTime() [1/2]
void DataCollector::resetTime (std::string tag, double value = 0)
Definition at line 416 of file data_collector.cpp.
{
    int index = findIndex(tag, TIME);
    if(index >= 0)
        times[index] = value;
}
Referenced by reset().
resetTexts()
void DataCollector::resetTexts () inline
Definition at line 82 of file data_collector.h.
{std::fill(text.begin(), text.end(), "");}
resetTimes()
void DataCollector::resetTimes (double value = 0) inline
Definition at line 83 of file data_collector.h.
{std::fill(times.begin(), times.end(), value);}
Referenced by PWDefault::resetIteration(), and Preprocessing::solveRound().
resetTimesCumulative()
void DataCollector::resetTimesCumulative (double value = 0) inline
Definition at line 84 of file data_collector.h.
{std::fill(times_cumulative.begin(), times_cumulative.end(), value);}
Referenced by PWDefault::resetAlgorithm().
resetIntegers()
void DataCollector::resetIntegers () inline
Definition at line 85 of file data_collector.h.
{ std::fill(integers.begin(), integers.end(), 0);}
resetDecimals()
void DataCollector::resetDecimals () inline
Definition at line 86 of file data_collector.h.
{std::fill(decimals.begin(), decimals.end(), 0);}
clearRecords()
void DataCollector::clearRecords () inline
Definition at line 88 of file data_collector.h.
{records.clear();}
clear()
void DataCollector::clear ()
Definition at line 422 of file data_collector.cpp.
{
    dict.clear();
    text.clear();
    times.clear();
    times_cumulative.clear();
    integers.clear();
    decimals.clear();
    tag_text.clear();
    tag_times.clear();
    tag_integers.clear();
    tag_decimals.clear();
}
setText()
void DataCollector::setText (int id, std::string text) inline
Direct access to Data
Definition at line 95 of file data_collector.h.
{this->text[id] = text;}
getText()
std::string DataCollector::getText (int id) inline
Definition at line 96 of file data_collector.h.
{return text[id];}
Referenced by print().
startTime() [2/2]
void DataCollector::startTime (int id) inline
Definition at line 99 of file data_collector.h.
{time_point[id] = std::chrono::high_resolution_clock::now();}
stopTime() [2/2]
void DataCollector::stopTime (int id)
Direct access to Data
Definition at line 439 of file data_collector.cpp.
{
    double time = std::chrono::duration<double>(std::chrono::high_resolution_clock::now() - time_point[id]).count();
    times[id] += time;
    times_cumulative[id] += time;
}
getTime()
double DataCollector::getTime (int id) inline
Definition at line 101 of file data_collector.h.
{return times[id];}
Referenced by print().
getTimeCumulative()
double DataCollector::getTimeCumulative (int id) inline
Definition at line 102 of file data_collector.h.
{return times_cumulative[id];}
Referenced by print().
resetTime() [2/2]
void DataCollector::resetTime (int id) inline
Definition at line 103 of file data_collector.h.
{times[id] = 0;}
resetTimeCumulative()
void DataCollector::resetTimeCumulative (int id) inline
Definition at line 104 of file data_collector.h.
{times_cumulative[id] = 0;}
setInteger()
void DataCollector::setInteger (int id, int value) inline
Definition at line 107 of file data_collector.h.
{this->integers[id] = value;}
incrementInteger()
void DataCollector::incrementInteger (int id, int value) inline
Definition at line 108 of file data_collector.h.
{integers[id] += value;}
getInt()
int DataCollector::getInt (int id) inline
Definition at line 109 of file data_collector.h.
{return integers[id];}
Referenced by print().
resetInteger()
void DataCollector::resetInteger (int id) inline
Definition at line 110 of file data_collector.h.
{integers[id] = 0;}
Referenced by reset().
setDecimal()
void DataCollector::setDecimal (int id, double value) inline
Definition at line 113 of file data_collector.h.
{decimals[id] = value;}
incrementDecimal()
void DataCollector::incrementDecimal (int id, double value) inline
Definition at line 114 of file data_collector.h.
{decimals[id] += value;}
getDecimal()
double DataCollector::getDecimal (int id) inline
Definition at line 115 of file data_collector.h.
{return decimals[id];}
Referenced by print().
resetDecimal()
void DataCollector::resetDecimal (int id) inline
Definition at line 116 of file data_collector.h.
{decimals[id] = 0;}
Referenced by reset().
Member Data Documentation
name
std::string DataCollector::name private
Definition at line 121 of file data_collector.h.
Referenced by DataCollector(), print(), setCollectionName(), and setOutputPath().
output_path
std::string DataCollector::output_path private
Definition at line 122 of file data_collector.h.
Referenced by setOutputPath(), and writeData().
dict
std::unordered_map<std::string, std::pair<int, int> > DataCollector::dict private
Definition at line 127 of file data_collector.h.
Referenced by addDictionary(), clear(), findIndex(), getDataStructure(), getValue(), print(), and reset().
tag_text
std::vector<std::string> DataCollector::tag_text private
Definition at line 130 of file data_collector.h.
Referenced by addDictionary(), clear(), print(), and setHeader().
text
std::vector<std::string> DataCollector::text private
Definition at line 131 of file data_collector.h.
Referenced by addDictionary(), clear(), collect(), getText(), getValue(), init(), print(), resetText(), resetTexts(), saveRecord(), and setText().
times
std::vector<double> DataCollector::times private
Definition at line 134 of file data_collector.h.
Referenced by addDictionary(), clear(), getTime(), getValue(), initTime(), print(), resetTime(), resetTime(), resetTimes(), saveRecord(), stopGlobalTime(), stopTime(), and stopTime().
times_cumulative
std::vector<double> DataCollector::times_cumulative private
Definition at line 134 of file data_collector.h.
Referenced by addDictionary(), clear(), getGlobalTime(), getGlobalTimeNow(), getTimeCumulative(), initTime(), print(), resetTimeCumulative(), resetTimesCumulative(), saveRecord(), stopGlobalTime(), stopTime(), and stopTime().
time_point
std::vector<std::chrono::time_point<std::chrono::high_resolution_clock> > DataCollector::time_point private
Definition at line 135 of file data_collector.h.
Referenced by addDictionary(), getGlobalTimeNow(), startGlobalTime(), startTime(), startTime(), stopGlobalTime(), stopTime(), and stopTime().
tag_times
std::vector<std::string> DataCollector::tag_times private
Definition at line 136 of file data_collector.h.
Referenced by addDictionary(), clear(), print(), and setHeader().
integers
std::vector<int> DataCollector::integers private
Definition at line 139 of file data_collector.h.
Referenced by addDictionary(), clear(), collect(), getInt(), getValue(), increment(), incrementInteger(), init(), print(), resetInteger(), resetIntegers(), saveRecord(), and setInteger().
tag_integers
std::vector<std::string> DataCollector::tag_integers private
Definition at line 140 of file data_collector.h.
Referenced by addDictionary(), clear(), print(), and setHeader().
decimals
std::vector<double> DataCollector::decimals private
Definition at line 143 of file data_collector.h.
Referenced by addDictionary(), clear(), collect(), getDecimal(), getValue(), increment(), incrementDecimal(), init(), print(), resetDecimal(), resetDecimals(), saveRecord(), and setDecimal().
tag_decimals
std::vector<std::string> DataCollector::tag_decimals private
Definition at line 144 of file data_collector.h.
Referenced by addDictionary(), clear(), print(), and setHeader().
header
std::string DataCollector::header private
Definition at line 147 of file data_collector.h.
Referenced by setHeader(), and writeData().
records
std::list<std::string> DataCollector::records private
Definition at line 148 of file data_collector.h.
Referenced by clearRecords(), saveRecord(), and writeData().
The documentation for this class was generated from the following files:
data_collector.h
data_collector.cpp