PathWyse: Bitset Class Reference
Bitset Class Reference
#include <bitset.h>
Public Member Functions
Bitset ()
Bitset (size_t num_bits, uint64_t value=0)
Bitset (const Bitset &b)
~Bitset ()=default
uint64_t count_extra_bits () const
void m_zero_unused_bits ()
Bitset & reset (size_t pos)
Bitset & reset ()
void init (size_t num_bits, uint64_t value)
size_t size () const
void resize (std::size_t num_bits, bool value)
void clear ()
Bitset & set (size_t pos, bool val=true)
Bitset & set ()
bool get (size_t pos)
template<typename ValueType >
std::size_t popcount (ValueType value)
template<typename T >
const unsigned char * object_representation (T *p)
template<typename Iterator >
size_t do_count (Iterator first, std::size_t length, bool access_by_bytes)
size_t count ()
Bitset & operator&= (const Bitset &rhs)
Bitset & operator|= (const Bitset &rhs)
bool empty () const
Bitset & flip ()
Bitset operator~ () const
bool any () const
bool none () const
Static Public Member Functions
static size_t bit_index (size_t pos)
static size_t block_index (size_t pos)
static uint64_t bit_mask (size_t pos)
static size_t calc_num_blocks (size_t num_bits)
Static Public Attributes
static const size_t bits_per_uint64 = std::numeric_limits<uint64_t>::digits
Private Types
typedef std::vector< uint64_t > buffer_type
Private Attributes
buffer_type m_bitset
std::size_t m_num_bits
Friends
bool operator== (const Bitset &a, const Bitset &b)
Detailed Description
Definition at line 45 of file bitset.h.
Member Typedef Documentation
buffer_type
typedef std::vector<uint64_t> Bitset::buffer_type private
Definition at line 46 of file bitset.h.
Constructor & Destructor Documentation
Bitset() [1/3]
Bitset::Bitset () inline
Definition at line 52 of file bitset.h.
: m_num_bits(0) {}
Bitset() [2/3]
Bitset::Bitset (size_t num_bits, uint64_t value = 0) inline
Definition at line 54 of file bitset.h.
    : m_num_bits(num_bits)
    {
        init(num_bits, value);
    }
Bitset() [3/3]
Bitset::Bitset (const Bitset & b) inline
Definition at line 59 of file bitset.h.
: m_bitset(b.m_bitset), m_num_bits(b.m_num_bits) {}
~Bitset()
Bitset::~Bitset () default
Member Function Documentation
count_extra_bits()
uint64_t Bitset::count_extra_bits () const inline
Definition at line 66 of file bitset.h.
{ return bit_index(m_num_bits); }
Referenced by m_zero_unused_bits().
bit_index()
static size_t Bitset::bit_index (size_t pos) inline static
Definition at line 67 of file bitset.h.
{return pos % bits_per_uint64;}
Referenced by bit_mask(), count_extra_bits(), and resize().
block_index()
static size_t Bitset::block_index (size_t pos) inline static
Definition at line 68 of file bitset.h.
{ return pos / bits_per_uint64; }
Referenced by get(), reset(), and set().
bit_mask()
static uint64_t Bitset::bit_mask (size_t pos) inline static
Definition at line 69 of file bitset.h.
{ return uint64_t(1) << bit_index(pos); }
Referenced by get(), and set().
calc_num_blocks()
static size_t Bitset::calc_num_blocks (size_t num_bits) inline static
Definition at line 70 of file bitset.h.
                                                   {return num_bits / bits_per_uint64
                                                           + static_cast<std::size_t>(num_bits % bits_per_uint64 != 0);}
Referenced by init(), m_zero_unused_bits(), and resize().
m_zero_unused_bits()
void Bitset::m_zero_unused_bits () inline
Definition at line 75 of file bitset.h.
    {
        assert (m_bitset.size() == calc_num_blocks(m_num_bits));
        const uint64_t extra_bits = count_extra_bits();
        if (extra_bits != 0)
            m_bitset.back() &= (uint64_t(1) << extra_bits) - 1;
    }
Referenced by flip(), resize(), and set().
reset() [1/2]
Bitset & Bitset::reset (size_t pos) inline
Definition at line 85 of file bitset.h.
{
        // reset the bit in position pos
        m_bitset[block_index(pos)] &= ~bit_mask(pos);
        return *this;
    }
Referenced by PWDefault::DssrRestricted(), and Dijkstra::resetAlgorithm().
reset() [2/2]
Bitset & Bitset::reset () inline
Definition at line 90 of file bitset.h.
    {
        std::fill(m_bitset.begin(), m_bitset.end(), uint64_t(0));
        return *this;
    }
Referenced by set().
init()
void Bitset::init (size_t num_bits, uint64_t value) inline
Definition at line 96 of file bitset.h.
{
        m_bitset.resize(calc_num_blocks(num_bits), value);
    }
Referenced by Bitset().
size()
size_t Bitset::size () const inline
Definition at line 100 of file bitset.h.
{
        return m_num_bits;
    }
Referenced by PWDefault::DssrRestricted(), empty(), operator&=(), and operator|=().
resize()
void Bitset::resize (std::size_t num_bits, bool value) inline
Definition at line 105 of file bitset.h.
{
        size_t old_size = m_bitset.size();
        size_t required_block = calc_num_blocks(num_bits);
        const uint64_t v = value? std::numeric_limits<uint64_t>::max() : 0;
        if (old_size != required_block) {
            this->m_bitset.resize(num_bits, v);
        }
        if (value && (num_bits > m_num_bits)) {
            // bistset has been increased
            size_t extra_bits = bit_index(m_num_bits);
            if (extra_bits) {
                assert(old_size >= 1 && old_size <= m_bitset.size());
                m_bitset[old_size - 1] |= (v << extra_bits);
            }
        }
        m_num_bits = num_bits;
        m_zero_unused_bits();
    }
clear()
void Bitset::clear () inline
Definition at line 127 of file bitset.h.
                 {
        m_bitset.clear();
        m_num_bits = 0;
    }
set() [1/2]
Bitset & Bitset::set (size_t pos, bool val = true) inline
Definition at line 133 of file bitset.h.
{
        assert(pos < m_num_bits);
        if (val)
            m_bitset[block_index(pos)] |= bit_mask(pos);
        else
            reset(pos);
        return *this;
    }
Referenced by Graph::activateNode(), PWDefault::DssrRestricted(), PWDefault::DssrStandard(), Graph::initGraph(), LabelAdv::initVisited(), PWDefault::NgRestricted(), Graph::pruneActiveNode(), Graph::resetActiveNodes(), LabelAdv::setUnreachable(), Dijkstra::solve(), and LabelAdv::updateLabel().
set() [2/2]
Bitset & Bitset::set () inline
Definition at line 143 of file bitset.h.
                  {
        std::fill(m_bitset.begin(), m_bitset.end(), std::numeric_limits<uint64_t>::max());
        m_zero_unused_bits();
        return *this;
    }
get()
bool Bitset::get (size_t pos) inline
Definition at line 149 of file bitset.h.
{
        assert (pos < m_num_bits);
        return (this->m_bitset[block_index(pos)] & bit_mask(pos)) != 0;
    }
Referenced by any(), bit_index(), bit_mask(), Bitset(), block_index(), calc_num_blocks(), count(), do_count(), PWDefault::DssrRestricted(), flip(), get(), init(), Graph::isActiveNode(), LabelAdv::isReachable(), m_zero_unused_bits(), PWDefault::NgRestricted(), none(), object_representation(), operator&=(), operator|=(), operator~(), popcount(), reset(), reset(), resize(), set(), and Dijkstra::solve().
popcount()
template<typename ValueType > std::size_t Bitset::popcount (ValueType value) inline
Definition at line 155 of file bitset.h.
{
        std::size_t num = 0u;
        while (value) {
            num += count_table<>::table[value & ((1u<<table_width) - 1)];
            value >>= table_width;
        }
        return num;
    }
object_representation()
template<typename T > const unsigned char * Bitset::object_representation (T * p) inline
Definition at line 165 of file bitset.h.
{
        return static_cast<const unsigned char *>(static_cast<const void *>(p));
    }
Referenced by do_count().
do_count()
template<typename Iterator > size_t Bitset::do_count (Iterator first, std::size_t length, bool access_by_bytes) inline
Definition at line 170 of file bitset.h.
{
        if(!access_by_bytes) {
            // Access by blocks
            std::size_t num1 = 0u, num2 = 0u;
            while (length >= 2u) {
                num1 += popcount<uint64_t>(*first);
                ++first;
                num2 += popcount<uint64_t>(*first);
                ++first;
                length -= 2u;
            }
            if (length > 0u)
                num1 += popcount<uint64_t>(*first);
            return num1 + num2;
        } else {
            // access by bytes
            if (length > 0u) {
                const unsigned char* p = object_representation(&*first);
                length *= sizeof(*first);
                return do_count(p, length, false);
            }
            return 0u;
        }
    }
Referenced by count(), and do_count().
count()
size_t Bitset::count () inline
Definition at line 198 of file bitset.h.
                  {
        enum { no_padding = bits_per_uint64 == CHAR_BIT * sizeof(uint64_t) };
        enum { enough_table_width = table_width >= CHAR_BIT };
        enum { uneffective_popcount = sizeof(uint64_t) < sizeof(unsigned int) };
        enum { mode = (no_padding && enough_table_width && uneffective_popcount)
                      ? true
                      : false };
        return do_count(m_bitset.begin(), m_bitset.size(), mode);
    }
Referenced by Graph::countActiveNodes(), PWDefault::DssrRestricted(), PWDefault::DssrStandard(), and PWDefault::NgRestricted().
operator&=()
Bitset & Bitset::operator&= (const Bitset & rhs) inline
Definition at line 208 of file bitset.h.
{
        assert(size() == rhs.size());
        for (size_t i = 0; i < m_bitset.size(); ++i)
            m_bitset[i] &= rhs.m_bitset[i];
        return *this;
    }
operator|=()
Bitset & Bitset::operator|= (const Bitset & rhs) inline
Definition at line 215 of file bitset.h.
{
        assert(size() == rhs.size());
        for (size_t i = 0; i < m_bitset.size(); ++i)
            m_bitset[i] |= rhs.m_bitset[i];
        return *this;
    }
empty()
bool Bitset::empty () const inline
Definition at line 222 of file bitset.h.
                      {
        return size() == 0;
    }
Referenced by LabelAdv::LabelAdv(), LabelAdv::operator=(), and LabelAdv::updateLabel().
flip()
Bitset & Bitset::flip () inline
Definition at line 226 of file bitset.h.
                  {
        for (size_t i = 0; i < m_bitset.size(); ++i)
            m_bitset[i] = ~m_bitset[i];
        m_zero_unused_bits();
        return *this;
    }
operator~()
Bitset Bitset::operator~ () const inline
Definition at line 233 of file bitset.h.
{
        Bitset b(*this);
        b.flip();
        return b;
    }
any()
bool Bitset::any () const inline
Definition at line 241 of file bitset.h.
                    {
        for (size_t i = 0; i < m_bitset.size(); ++i)
            if (m_bitset[i])
                return true;
        return false;
    }
Referenced by none().
none()
bool Bitset::none () const inline
Definition at line 248 of file bitset.h.
                     {
        return not any();
    }
Friends And Related Symbol Documentation
operator==
bool operator== (const Bitset & a, const Bitset & b) friend
Definition at line 31 of file bitset.cpp.
{
    return (a.m_num_bits == b.m_num_bits)
           && (a.m_bitset == b.m_bitset);
}
Member Data Documentation
bits_per_uint64
const size_t Bitset::bits_per_uint64 = std::numeric_limits<uint64_t>::digits static
Definition at line 49 of file bitset.h.
Referenced by bit_index(), block_index(), calc_num_blocks(), and count().
m_bitset
buffer_type Bitset::m_bitset private
Definition at line 253 of file bitset.h.
Referenced by any(), clear(), count(), flip(), get(), init(), m_zero_unused_bits(), operator&=(), operator|=(), reset(), reset(), resize(), set(), and set().
m_num_bits
std::size_t Bitset::m_num_bits private
Definition at line 254 of file bitset.h.
Referenced by clear(), count_extra_bits(), get(), m_zero_unused_bits(), resize(), set(), and size().
The documentation for this class was generated from the following file:
bitset.h