PathWyse: ResourceData Struct Reference
ResourceData Struct Reference abstract
#include <resource_data.h>
Public Member Functions
ResourceData (int n_nodes)
virtual ~ResourceData ()=default
virtual void reset ()
void setNodeCosts (std::vector< int > node_costs)
void setNodeCost (int id, int cost)
void increaseNodeCost (int id, int delta)
void multiplyNodeCost (int id, float factor)
int getNodeCost (int id)
std::vector< int > & getNodeCost ()
virtual void setArcCost (int i, int j, int cost)=0
virtual void increaseArcCost (int i, int j, int delta)=0
virtual void multiplyArcCost (int i, int j, float factor)=0
virtual int getArcCost (int i, int j)=0
virtual void scaleData (float scaling)=0
Protected Attributes
int n_nodes
std::vector< int > node_costs
Detailed Description
Definition at line 7 of file resource_data.h.
Constructor & Destructor Documentation
ResourceData()
ResourceData::ResourceData (int n_nodes) inline explicit
Resource data management
Definition at line 11 of file resource_data.h.
{this->n_nodes = n_nodes;}
~ResourceData()
virtual ResourceData::~ResourceData () virtual default
Member Function Documentation
reset()
virtual void ResourceData::reset () inline virtual
Reimplemented in ResourceDataMap, and ResourceDataMatrix.
Definition at line 14 of file resource_data.h.
{node_costs.clear();};
Referenced by ResourceDataMap::reset(), and ResourceDataMatrix::reset().
setNodeCosts()
void ResourceData::setNodeCosts (std::vector< int > node_costs) inline
Node Data
Definition at line 17 of file resource_data.h.
{this->node_costs = node_costs;}
Referenced by Resource::setNodeCosts().
setNodeCost()
void ResourceData::setNodeCost (int id, int cost) inline
Definition at line 18 of file resource_data.h.
{
        if(node_costs.empty())
            node_costs.resize(n_nodes, 0);
        node_costs[id] = cost;
    }
Referenced by Resource::setNodeCost().
increaseNodeCost()
void ResourceData::increaseNodeCost (int id, int delta) inline
Definition at line 24 of file resource_data.h.
{
        if(not node_costs.empty())
            node_costs[id] += delta;
    }
Referenced by Resource::increaseNodeCost().
multiplyNodeCost()
void ResourceData::multiplyNodeCost (int id, float factor) inline
Definition at line 29 of file resource_data.h.
{
        if(not node_costs.empty())
            node_costs[id] *= factor;
    }
Referenced by Resource::multiplyNodeCost(), ResourceDataMap::scaleData(), and ResourceDataMatrix::scaleData().
getNodeCost() [1/2]
int ResourceData::getNodeCost (int id) inline
Definition at line 34 of file resource_data.h.
{return node_costs.empty() ? 0: node_costs[id];}
Referenced by Capacity::extend(), DefaultCost::extend(), Time::extend(), TimeWindow::extend(), Resource::getNodeCost(), TimeWindow::init(), TimeWindow::isFeasible(), TimeWindow::join(), Capacity::join(), DefaultCost::join(), Time::join(), and TimeWindow::join().
getNodeCost() [2/2]
std::vector< int > & ResourceData::getNodeCost () inline
Definition at line 35 of file resource_data.h.
{return node_costs;}
setArcCost()
virtual void ResourceData::setArcCost (int i, int j, int cost) pure virtual
Arc Data
Implemented in ResourceDataMap, and ResourceDataMatrix.
Referenced by Resource::setArcCost().
increaseArcCost()
virtual void ResourceData::increaseArcCost (int i, int j, int delta) pure virtual
Implemented in ResourceDataMap, and ResourceDataMatrix.
Referenced by Resource::increaseArcCost().
multiplyArcCost()
virtual void ResourceData::multiplyArcCost (int i, int j, float factor) pure virtual
Implemented in ResourceDataMap, and ResourceDataMatrix.
Referenced by Resource::multiplyArcCost().
getArcCost()
virtual int ResourceData::getArcCost (int i, int j) pure virtual
Implemented in ResourceDataMap, and ResourceDataMatrix.
Referenced by DefaultCost::extend(), Time::extend(), TimeWindow::extend(), Resource::getArcCost(), TimeWindow::init(), DefaultCost::join(), Time::join(), and TimeWindow::join().
scaleData()
virtual void ResourceData::scaleData (float scaling) pure virtual
Scaling
Implemented in ResourceDataMap, and ResourceDataMatrix.
Referenced by Resource::scaleResource().
Member Data Documentation
n_nodes
int ResourceData::n_nodes protected
Definition at line 47 of file resource_data.h.
Referenced by ResourceData(), ResourceDataMap::ResourceDataMap(), ResourceDataMatrix::ResourceDataMatrix(), ResourceDataMap::scaleData(), ResourceDataMatrix::scaleData(), and setNodeCost().
node_costs
std::vector<int> ResourceData::node_costs protected
Definition at line 48 of file resource_data.h.
Referenced by getNodeCost(), getNodeCost(), increaseNodeCost(), multiplyNodeCost(), reset(), setNodeCost(), and setNodeCosts().
The documentation for this struct was generated from the following file:
resource_data.h