PathWyse: Parameters Struct Reference
Parameters Struct Reference
#include <param.h>
Static Public Member Functions
static void readParameters (std::string param_path)
static std::string getInstancePath ()
static int getVerbosity ()
static void setVerbosity (int v)
static std::string getMainAlgorithmName ()
static std::vector< std::string > & getEnsembleNames ()
static bool isEnsembleUsed ()
static int getCompressionThreshold ()
static bool parseConsole (int argc, char **argv)
static int getOrigin ()
static int getDestination ()
static int getCriticalUB ()
static bool isScalingOverridden ()
static float getScaling ()
static std::string getScalingTarget ()
static float getCoordScaling ()
static int getCoordDistanceType ()
static float getCoordDistanceScaling ()
static bool isPreprocessingCritical ()
static bool isDefaultAutoConfigured ()
static float getDefaultTimelimit ()
static bool isDefaultParallel ()
static bool isDefaultBidirectional ()
static double getDefaultSplit ()
static int getDefaultReserve ()
static bool isDefaultUsingVisited ()
static bool isDefaultUsingUnreachables ()
static int getDefaultDSSR ()
static int getDefaultNG ()
static int getDefaultNGSize ()
static int getDefaultRelaxationQueueLimit ()
static int getDefaultCandidateType ()
static int getDefaultJoinType ()
static bool isDefaultJoinEarly ()
static unsigned long long int getDefaultJoinStep ()
static bool isOutputStored ()
static bool isCollecting ()
static int getCollectionLevel ()
static std::string getCollectionOutput ()
static std::string getCollectionTag ()
static void setCollectionTag (std::string tag)
static std::string getTimestamp ()
static std::string getCollectionPath ()
static void setTimestamp (std::string t)
static void setupCollectionPath ()
Static Private Attributes
static std::string param_path = "pathwyse.set"
static std::string instance_path = "input.txt"
static int verbosity = 2
static std::string main_algorithm_name = "PWDefault"
static std::vector< std::string > ensemble_algorithms_names = {"PWDefaultRelaxDom","PWDefaultRelaxQueue"}
static bool use_ensemble = false
static int memory_threshold = 10000
static int origin = -1
static int destination = -1
static int ub_critical = -1
static bool scaling_override = false
static float scaling_value = 100.0
static std::string scaling_target = "objective"
static float coord_scaling = 1.0
static int coord_distance_type = DIST_NONE
static float coord_distance_scaling = 0.95
static bool preprocessing_critical = false
static float default_timelimit = 0
static bool default_parallel = true
static bool default_bidirectional = true
static bool default_use_visited = true
static int default_dssr = 1
static int default_ng = 0
static int default_ng_size = 8
static bool default_earlyjoin = false
static unsigned long long int default_earlyjoin_step = 300
static bool default_autoconfig = true
static double default_split = 0.5
static int default_reserve = 10000000
static bool default_compare_unreachables = true
static int default_candidate_type = 1
static int default_join_type = 2
static int default_queue_limit = 10
static bool output_write = false
static std::string timestamp = "YYYY-MM-DD_hh:mm:ss"
static int collection_level = -1
static std::string collection_folder = "output/"
static std::string collection_tag
static std::string collection_path
Detailed Description
Definition at line 11 of file param.h.
Member Function Documentation
readParameters()
void Parameters::readParameters (std::string param_path) static
Definition at line 69 of file param.cpp.
{
    std::ifstream f;
    std::string command, value;
    char separator;
    f.open(param_path.empty() ? Parameters::param_path : param_path);
    if(f) {
        while(f >> command >> separator >> value) {
            if(command == "verbosity")
                verbosity = stoi(value);
            else if(command == "main_algorithm")
                main_algorithm_name = value;
            else if(command == "ensemble/algorithms"){
                ensemble_algorithms_names.clear();
                std::string name;
                std::stringstream value_stream(value);
                while (std::getline(value_stream, name, ','))
                    ensemble_algorithms_names.emplace_back(name);
            }
            else if(command == "ensemble/active")
                use_ensemble = stoi(value);
            else if(command == "problem/coordinates/distance") {
                if(value == "euclidean")
                    coord_distance_type = DIST_EUCLIDEAN;
                else if(value == "haversine")
                    coord_distance_type = DIST_HAVERSINE;
                else if(value == "equirectangular")
                    coord_distance_type = DIST_EQUIRECTANGULAR;
            }
            else if(command == "problem/coordinates/distance/scaling")
                coord_distance_scaling = stof(value);
            else if(command == "problem/coordinates/microdegrees") {
                if(stof(value) > 0)
                    coord_scaling = 1/1e6;
            }
            else if(command == "problem/memory_threshold")
                memory_threshold = stoi(value);
            else if(command == "problem/scaling/override")
                scaling_override = stoi(value);
            else if(command == "problem/scaling"){
                scaling_value = stof(value);
            }
            else if(command == "problem/scaling/target")
                scaling_target = value;
            else if(command == "algorithm/preprocessing/critical")
                preprocessing_critical = stoi(value);
            else if(command == "algo/default/autoconfig")
                default_autoconfig = stoi(value);
            else if(command == "algo/default/timelimit")
                default_timelimit = stof(value);
            else if(command == "algo/default/parallel")
                default_parallel = stoi(value);
            else if(command == "algo/default/bidirectional")
                default_bidirectional = stoi(value);
            else if(command == "algo/default/bidirectional/split")
                default_split = stof(value);
            else if(command == "algo/default/reserve")
                default_reserve = stoi(value);
            else if(command == "algo/default/use_visited")
                default_use_visited= stoi(value);
            else if(command == "algo/default/compare_unreachables")
                default_compare_unreachables = stoi(value);
            else if(command == "algo/default/dssr") {
                if(value ==  "off")
                    default_dssr = DSSR_OFF;
                else if(value == "restricted")
                    default_dssr = DSSR_RESTRICTED;
                else
                    default_dssr = DSSR_STANDARD;
            }
            else if(command == "algo/default/ng") {
                if(value ==  "off")
                    default_ng = NG_OFF;
                else if(value == "restricted")
                    default_ng = NG_RESTRICTED;
                else
                    default_ng = NG_STANDARD;
            }
            else if(command == "algo/default/ng/set_size")
                default_ng_size = stoi(value);
            else if(command == "algo/default/candidate/type") {
                if(value == "round-robin")
                    default_candidate_type = CANDIDATE_RR;
                else
                    default_candidate_type = CANDIDATE_NODE;
            }
            else if(command == "algo/default/join/type") {
                if(value == "classic")
                    default_join_type = JOIN_CLASSIC;
                else if(value == "naive")
                    default_join_type = JOIN_NAIVE;
                else
                    default_join_type = JOIN_ORDERED;
            }
            else if(command == "algo/default/join/early")
                default_earlyjoin = stoi(value);
            else if(command == "algo/default/join/early/step")
                default_earlyjoin_step = stoi(value);
            else if(command == "algo/default/relaxations/queue_limit")
                default_queue_limit = stoi(value);
            else if(command == "data_collection/level")
                collection_level = stoi(value);
            else if(command == "data_collection/tag") {
                if(collection_tag.empty())
                    collection_tag = value;
            }
            else if(command == "output/write")
                output_write = stoi(value);
        }
        f.close();
    }
    else std::cout<<"Warning: No param file found!"<<std::endl;
    if(not isCollecting())
        output_write = false;
}
Referenced by Solver::readConfiguration().
getInstancePath()
static std::string Parameters::getInstancePath () inline static
Solver Parameters
Definition at line 16 of file param.h.
{return instance_path;}
Referenced by Solver::readConfiguration().
getVerbosity()
static int Parameters::getVerbosity () inline static
Definition at line 17 of file param.h.
{return verbosity;}
Referenced by LMDefault::closeLabels(), LMDefault::findLabels(), LMDefault::join(), PWDefault::labeling(), PWAcyclic::preprocessing(), DataCollector::print(), DataCollector::print(), Solver::printBestSolution(), LMDefault::printCandidates(), LMDefault::printClosed(), Label::printLabel(), Path::printPath(), Problem::printProblem(), Solver::printStatus(), LMDefault::printStepConsumption(), Solver::printWelcome(), Preprocessing::pruneCritical(), Preprocessing::pruning(), Problem::readProblem(), Problem::readSparseProblem(), Solver::revertScaleData(), Solver::scaleData(), Solver::solve(), PWDefault::solve(), Dijkstra::solve(), Solver::solveAlgorithm(), and Preprocessing::solveRound().
setVerbosity()
static void Parameters::setVerbosity (int v) inline static
Definition at line 18 of file param.h.
{verbosity = v;}
Referenced by Solver::setConsoleVerbosity().
getMainAlgorithmName()
static std::string Parameters::getMainAlgorithmName () inline static
Definition at line 21 of file param.h.
{return main_algorithm_name;}
Referenced by Solver::readConfiguration().
getEnsembleNames()
static std::vector< std::string > & Parameters::getEnsembleNames () inline static
Definition at line 22 of file param.h.
{return ensemble_algorithms_names;}
Referenced by Solver::readConfiguration().
isEnsembleUsed()
static bool Parameters::isEnsembleUsed () inline static
Definition at line 23 of file param.h.
{return use_ensemble;}
Referenced by Solver::readConfiguration().
getCompressionThreshold()
static int Parameters::getCompressionThreshold () inline static
Problem parameters
Definition at line 26 of file param.h.
{return memory_threshold;}
Referenced by Problem::initProblem().
parseConsole()
bool Parameters::parseConsole (int argc, char ** argv) static
Definition at line 203 of file param.cpp.
{
    bool success = false;
    if(argc <= 1) {
        std::cout<<"Instance file is missing...terminating."<<std::endl;
        return success;
    }
    instance_path = argv[1];
    success = true;
    int pos = 2;
    std::string command;
    while(pos < argc) {
        command = argv[pos++];
        if(pos  == argc) {
            std::cout<<"Missing value for parameter: " << command <<", terminating..." <<std::endl;
            return success = false;
        }
        if(command == "-o")
            origin = atoi(argv[pos++]);
        else if(command == "-d")
            destination = atoi(argv[pos++]);
        else if(command == "-ub")
            ub_critical = atoi(argv[pos++]);
        else if(command == "-param")
            param_path = argv[pos++];
        else if(command == "-tag")
            collection_tag = argv[pos++];
        else {
            std::cout<<"Parameter: " << command << " not recognized, terminating..." <<std::endl;
            return success = false;
        }
    }
    return success;
}
Referenced by main().
getOrigin()
static int Parameters::getOrigin () inline static
Definition at line 30 of file param.h.
{return origin;}
Referenced by Problem::readProblem(), and Problem::readSparseProblem().
getDestination()
static int Parameters::getDestination () inline static
Definition at line 31 of file param.h.
{return destination;}
Referenced by Problem::readProblem(), and Problem::readSparseProblem().
getCriticalUB()
static int Parameters::getCriticalUB () inline static
Definition at line 32 of file param.h.
{return ub_critical;}
Referenced by Problem::readProblem(), and Problem::readSparseProblem().
isScalingOverridden()
static bool Parameters::isScalingOverridden () inline static
Definition at line 35 of file param.h.
{return scaling_override;}
Referenced by Solver::revertScaleData(), and Solver::scaleData().
getScaling()
static float Parameters::getScaling () inline static
Definition at line 36 of file param.h.
{return scaling_value;}
Referenced by Solver::revertScaleData(), and Solver::scaleData().
getScalingTarget()
static std::string Parameters::getScalingTarget () inline static
Definition at line 37 of file param.h.
{return scaling_target;}
Referenced by Solver::revertScaleData(), and Solver::scaleData().
getCoordScaling()
static float Parameters::getCoordScaling () inline static
Definition at line 40 of file param.h.
{return coord_scaling;}
Referenced by Graph::getCoordDistance().
getCoordDistanceType()
static int Parameters::getCoordDistanceType () inline static
Definition at line 41 of file param.h.
{return coord_distance_type;}
Referenced by Graph::getCoordDistance().
getCoordDistanceScaling()
static float Parameters::getCoordDistanceScaling () inline static
Definition at line 42 of file param.h.
{return coord_distance_scaling;}
Referenced by Graph::getCoordDistance().
isPreprocessingCritical()
static bool Parameters::isPreprocessingCritical () inline static
Preprocessing algorithm
Definition at line 45 of file param.h.
{return preprocessing_critical;}
Referenced by Dijkstra::checkFeasibility(), and Preprocessing::Preprocessing().
isDefaultAutoConfigured()
static bool Parameters::isDefaultAutoConfigured () inline static
Default Algorithm
Definition at line 48 of file param.h.
{return default_autoconfig;}
Referenced by LMDefault::readConfiguration().
getDefaultTimelimit()
static float Parameters::getDefaultTimelimit () inline static
Definition at line 49 of file param.h.
{return default_timelimit;}
Referenced by PWDefault::readConfiguration().
isDefaultParallel()
static bool Parameters::isDefaultParallel () inline static
Definition at line 50 of file param.h.
{return default_parallel;}
Referenced by PWDefault::readConfiguration().
isDefaultBidirectional()
static bool Parameters::isDefaultBidirectional () inline static
Definition at line 51 of file param.h.
{return default_bidirectional;}
Referenced by LMDefault::readConfiguration(), and PWDefault::readConfiguration().
getDefaultSplit()
static double Parameters::getDefaultSplit () inline static
Definition at line 52 of file param.h.
{return default_split;}
Referenced by LMDefault::readConfiguration().
getDefaultReserve()
static int Parameters::getDefaultReserve () inline static
Definition at line 53 of file param.h.
{return default_reserve;}
Referenced by LMDefault::readConfiguration().
isDefaultUsingVisited()
static bool Parameters::isDefaultUsingVisited () inline static
Definition at line 55 of file param.h.
{return default_use_visited;}
Referenced by LMDefault::readConfiguration(), and PWDefault::readConfiguration().
isDefaultUsingUnreachables()
static bool Parameters::isDefaultUsingUnreachables () inline static
Definition at line 56 of file param.h.
{return default_compare_unreachables;}
Referenced by LMDefault::readConfiguration().
getDefaultDSSR()
static int Parameters::getDefaultDSSR () inline static
Definition at line 57 of file param.h.
{return default_dssr;}
Referenced by PWDefault::readConfiguration().
getDefaultNG()
static int Parameters::getDefaultNG () inline static
Definition at line 58 of file param.h.
{return default_ng;}
Referenced by PWDefault::readConfiguration().
getDefaultNGSize()
static int Parameters::getDefaultNGSize () inline static
Definition at line 59 of file param.h.
{return default_ng_size;}
Referenced by PWDefault::readConfiguration().
getDefaultRelaxationQueueLimit()
static int Parameters::getDefaultRelaxationQueueLimit () inline static
Definition at line 61 of file param.h.
{return default_queue_limit;}
Referenced by PWDefault::readConfiguration().
getDefaultCandidateType()
static int Parameters::getDefaultCandidateType () inline static
Definition at line 63 of file param.h.
{return default_candidate_type;}
Referenced by LMDefault::readConfiguration().
getDefaultJoinType()
static int Parameters::getDefaultJoinType () inline static
Definition at line 64 of file param.h.
{return default_join_type;}
Referenced by LMDefault::readConfiguration().
isDefaultJoinEarly()
static bool Parameters::isDefaultJoinEarly () inline static
Definition at line 65 of file param.h.
{return default_earlyjoin;}
Referenced by PWDefault::readConfiguration().
getDefaultJoinStep()
static unsigned long long int Parameters::getDefaultJoinStep () inline static
Definition at line 66 of file param.h.
{return default_earlyjoin_step;}
Referenced by PWDefault::readConfiguration().
isOutputStored()
static bool Parameters::isOutputStored () inline static
Data Collection
Definition at line 69 of file param.h.
{return output_write;}
Referenced by DataCollector::saveRecord(), DataCollector::setHeader(), Solver::setupOutput(), and DataCollector::writeData().
isCollecting()
static bool Parameters::isCollecting () inline static
Definition at line 70 of file param.h.
{return collection_level >= 0;}
Referenced by LMacyclic::collectData(), PWAcyclic::collectData(), LMDefault::collectData(), PWDefault::collectData(), Problem::collectData(), Algorithm::collectSolution(), DataCollector::findIndex(), Algorithm::initDataCollection(), LMacyclic::initDataCollection(), PWAcyclic::initDataCollection(), LMDefault::initDataCollection(), PWDefault::initDataCollection(), Preprocessing::initDataCollection(), Problem::initDataCollection(), DataCollector::print(), DataCollector::print(), readParameters(), DataCollector::reset(), and LMDefault::update_split().
getCollectionLevel()
static int Parameters::getCollectionLevel () inline static
Definition at line 71 of file param.h.
{return collection_level;}
Referenced by PWDefault::extend(), and PWDefault::initDataCollection().
getCollectionOutput()
static std::string Parameters::getCollectionOutput () inline static
Definition at line 72 of file param.h.
{return collection_folder;}
getCollectionTag()
static std::string Parameters::getCollectionTag () inline static
Definition at line 73 of file param.h.
{return collection_tag;}
setCollectionTag()
static void Parameters::setCollectionTag (std::string tag) inline static
Definition at line 74 of file param.h.
{collection_tag = tag;}
getTimestamp()
static std::string Parameters::getTimestamp () inline static
Definition at line 75 of file param.h.
{return timestamp;}
getCollectionPath()
static std::string Parameters::getCollectionPath () inline static
Definition at line 76 of file param.h.
{return collection_path;}
Referenced by DataCollector::setOutputPath(), and Solver::setupOutput().
setTimestamp()
static void Parameters::setTimestamp (std::string t) inline static
Definition at line 77 of file param.h.
{timestamp = t;}
Referenced by Solver::setupOutput().
setupCollectionPath()
void Parameters::setupCollectionPath () static
Definition at line 187 of file param.cpp.
{
    collection_path = collection_folder + "/" + timestamp;
    collection_path += (collection_tag != "" ? "[" + collection_tag + "]" : "");
    int name_count = 1;
    std::string tmp_path = collection_path;
    while(std::filesystem::exists(tmp_path)){
        tmp_path = collection_path + "_" + std::to_string(name_count);
        name_count++;
    }
    collection_path = tmp_path + "/";
}
Referenced by Solver::setupOutput().
Member Data Documentation
param_path
std::string Parameters::param_path = "pathwyse.set" static private
Default Values
Definition at line 81 of file param.h.
Referenced by parseConsole(), and readParameters().
instance_path
std::string Parameters::instance_path = "input.txt" static private
Solver Parameters
Definition at line 84 of file param.h.
Referenced by parseConsole().
verbosity
int Parameters::verbosity = 2 static private
Definition at line 85 of file param.h.
Referenced by getVerbosity(), readParameters(), and setVerbosity().
main_algorithm_name
std::string Parameters::main_algorithm_name = "PWDefault" static private
Definition at line 86 of file param.h.
Referenced by getMainAlgorithmName(), and readParameters().
ensemble_algorithms_names
std::vector< std::string > Parameters::ensemble_algorithms_names = {"PWDefaultRelaxDom","PWDefaultRelaxQueue"} static private
Definition at line 16 of file param.h.
{return instance_path;}
Referenced by getEnsembleNames(), and readParameters().
use_ensemble
bool Parameters::use_ensemble = false static private
Definition at line 88 of file param.h.
Referenced by isEnsembleUsed(), and readParameters().
memory_threshold
int Parameters::memory_threshold = 10000 static private
Problem parameters
Definition at line 91 of file param.h.
Referenced by getCompressionThreshold(), and readParameters().
origin
int Parameters::origin = -1 static private
Definition at line 94 of file param.h.
Referenced by getOrigin(), and parseConsole().
destination
int Parameters::destination = -1 static private
Definition at line 95 of file param.h.
Referenced by getDestination(), and parseConsole().
ub_critical
int Parameters::ub_critical = -1 static private
Definition at line 96 of file param.h.
Referenced by getCriticalUB(), and parseConsole().
scaling_override
bool Parameters::scaling_override = false static private
Definition at line 99 of file param.h.
Referenced by isScalingOverridden(), and readParameters().
scaling_value
float Parameters::scaling_value = 100.0 static private
Definition at line 100 of file param.h.
Referenced by getScaling(), and readParameters().
scaling_target
std::string Parameters::scaling_target = "objective" static private
Definition at line 101 of file param.h.
Referenced by getScalingTarget(), and readParameters().
coord_scaling
float Parameters::coord_scaling = 1.0 static private
Definition at line 104 of file param.h.
Referenced by getCoordScaling(), and readParameters().
coord_distance_type
int Parameters::coord_distance_type = DIST_NONE static private
Definition at line 105 of file param.h.
Referenced by getCoordDistanceType(), and readParameters().
coord_distance_scaling
float Parameters::coord_distance_scaling = 0.95 static private
Definition at line 106 of file param.h.
Referenced by getCoordDistanceScaling(), and readParameters().
preprocessing_critical
bool Parameters::preprocessing_critical = false static private
Preprocessing type
Definition at line 109 of file param.h.
Referenced by isPreprocessingCritical(), and readParameters().
default_timelimit
float Parameters::default_timelimit = 0 static private
Default Algorithm (PWDefault) Parameters
Definition at line 112 of file param.h.
Referenced by getDefaultTimelimit(), and readParameters().
default_parallel
bool Parameters::default_parallel = true static private
Definition at line 113 of file param.h.
Referenced by isDefaultParallel(), and readParameters().
default_bidirectional
bool Parameters::default_bidirectional = true static private
Definition at line 114 of file param.h.
Referenced by isDefaultBidirectional(), and readParameters().
default_use_visited
bool Parameters::default_use_visited = true static private
Definition at line 115 of file param.h.
Referenced by isDefaultUsingVisited(), and readParameters().
default_dssr
int Parameters::default_dssr = 1 static private
Definition at line 116 of file param.h.
Referenced by getDefaultDSSR(), and readParameters().
default_ng
int Parameters::default_ng = 0 static private
Definition at line 117 of file param.h.
Referenced by getDefaultNG(), and readParameters().
default_ng_size
int Parameters::default_ng_size = 8 static private
Definition at line 118 of file param.h.
Referenced by getDefaultNGSize(), and readParameters().
default_earlyjoin
bool Parameters::default_earlyjoin = false static private
Definition at line 119 of file param.h.
Referenced by isDefaultJoinEarly(), and readParameters().
default_earlyjoin_step
unsigned long long int Parameters::default_earlyjoin_step = 300 static private
Definition at line 120 of file param.h.
Referenced by getDefaultJoinStep(), and readParameters().
default_autoconfig
bool Parameters::default_autoconfig = true static private
Default Algorithm (PWDefault) Parameters
Definition at line 123 of file param.h.
Referenced by isDefaultAutoConfigured(), and readParameters().
default_split
double Parameters::default_split = 0.5 static private
Definition at line 124 of file param.h.
Referenced by getDefaultSplit(), and readParameters().
default_reserve
int Parameters::default_reserve = 10000000 static private
Definition at line 125 of file param.h.
Referenced by getDefaultReserve(), and readParameters().
default_compare_unreachables
bool Parameters::default_compare_unreachables = true static private
Definition at line 126 of file param.h.
Referenced by isDefaultUsingUnreachables(), and readParameters().
default_candidate_type
int Parameters::default_candidate_type = 1 static private
Definition at line 127 of file param.h.
Referenced by getDefaultCandidateType(), and readParameters().
default_join_type
int Parameters::default_join_type = 2 static private
Definition at line 128 of file param.h.
Referenced by getDefaultJoinType(), and readParameters().
default_queue_limit
int Parameters::default_queue_limit = 10 static private
Definition at line 131 of file param.h.
Referenced by getDefaultRelaxationQueueLimit(), and readParameters().
output_write
bool Parameters::output_write = false static private
Data Collection
Definition at line 134 of file param.h.
Referenced by isOutputStored(), and readParameters().
timestamp
std::string Parameters::timestamp = "YYYY-MM-DD_hh:mm:ss" static private
Definition at line 135 of file param.h.
Referenced by getTimestamp(), setTimestamp(), and setupCollectionPath().
collection_level
int Parameters::collection_level = -1 static private
Definition at line 136 of file param.h.
Referenced by getCollectionLevel(), isCollecting(), and readParameters().
collection_folder
std::string Parameters::collection_folder = "output/" static private
Definition at line 137 of file param.h.
Referenced by getCollectionOutput(), and setupCollectionPath().
collection_tag
std::string Parameters::collection_tag static private
Definition at line 137 of file param.h.
Referenced by getCollectionTag(), parseConsole(), readParameters(), setCollectionTag(), and setupCollectionPath().
collection_path
std::string Parameters::collection_path static private
Definition at line 137 of file param.h.
Referenced by getCollectionPath(), and setupCollectionPath().
The documentation for this struct was generated from the following files:
param.h
param.cpp