PathWyse: Preprocessing Class Reference
Preprocessing Class Reference
#include <preprocessing.h>
Public Member Functions
Preprocessing (std::string name, Problem *problem)
~Preprocessing ()
void solve () override
bool solveRound (bool direction, int res_id, double bounding=1)
void resetAlgorithm (int reset_level) override
double getSplit ()
void pruning ()
void pruneCritical ()
void initDataCollection ()
void collectData ()
Public Member Functions inherited from Algorithm
Algorithm (std::string name, Problem *problem)
virtual ~Algorithm ()=default
void initAlgorithm ()
void setName (std::string name)
std::string getName ()
int getStatus ()
void setStatus (int status)
void setExecutionID (int id)
int getExecutionID ()
void setType (std::string type)
std::string getType ()
Problem * getProblem ()
void setProblem (Problem *problem)
bool updateIncumbent (int value)
void setIncumbent (int value)
int getIncumbent ()
bool updateLowerBound (int value)
void setLowerBound (int value)
int getLowerBound ()
double getGlobalTime ()
Path * getBestSolution ()
void updateBestSolution (int id)
std::vector< Path > & getSolutions ()
void addSolution (Path &path)
void buildPath (int objective, Label *forward_label, Label *backward_label=nullptr)
void printStatus ()
void initDataCollection ()
void collectSolution (int id)
Protected Attributes
int round
bool preprocessingCritical
Bitset criticalActive
Dijkstra * dijkstra
Protected Attributes inherited from Algorithm
Problem * problem
std::string name
std::string algo_type
bool parallel
bool bidirectional
int executionID
int iterations
int algo_status
int incumbent
int lower_bound
int best_solution_id
std::vector< Path > solutions
DataCollector collector
DataCollector collector_sol
Detailed Description
Definition at line 7 of file preprocessing.h.
Constructor & Destructor Documentation
Preprocessing()
Preprocessing::Preprocessing (std::string name, Problem * problem) explicit
Algorithm management
Definition at line 5 of file preprocessing.cpp.
                                                            : Algorithm(name, problem) {
    initDataCollection();
    dijkstra = new Dijkstra(name, problem);
    preprocessingCritical = Parameters::isPreprocessingCritical();
    if(preprocessingCritical)
        criticalActive = Bitset(problem->getNumNodes());
    round = 0;
    setStatus(ALGO_READY);
}
~Preprocessing()
Preprocessing::~Preprocessing () inline
Definition at line 14 of file preprocessing.h.
{delete dijkstra;}
Member Function Documentation
solve()
void Preprocessing::solve () override virtual
Implements Algorithm.
Definition at line 17 of file preprocessing.cpp.
{
    setStatus(ALGO_OPTIMIZING);
    //Round 1B: Resource, Backward
    bool preprocess = solveRound(false, RES_CRITICAL);
    //Round 1F: Resource, Forward
    if(preprocess)
        preprocess = solveRound(true, RES_CRITICAL);
    //Round 2B: Cost, Backward
    if(preprocess)
        preprocess = solveRound(false, RES_COST);
    //Round 2F: Cost, Forward
    if(preprocess)
        preprocess  = solveRound(true, RES_COST);
    setStatus(ALGO_DONE);
    collector.writeData();
}
Referenced by PWAcyclic::preprocessing().
solveRound()
bool Preprocessing::solveRound (bool direction, int res_id, double bounding = 1)
Definition at line 40 of file preprocessing.cpp.
{
    collector.resetTimes();
    collector.startGlobalTime();
    bool preprocess = true;
    if(Parameters::getVerbosity() >= 3) {
        if(round == 0) std::cout<<"--------"<<std::endl;
        std::cout<<"Preprocessing, round: "<< round << std::endl;
    }
    if(preprocessingCritical and res_id == RES_CRITICAL)
        bounding = 0.5;
    dijkstra->initAlgorithm(direction, res_id, bounding);
    dijkstra->solve();
    if(res_id == RES_COST)
        lower_bound = dijkstra->getDistance(direction? problem->getDestination() : problem->getOrigin());
    if(problem->getStatus() != PROBLEM_INFEASIBLE){
        if(dijkstra->foundOptimal()){
            dijkstra->managePaths();
            auto bestPath = dijkstra->getBestSolution();
            addSolution(*bestPath);
            preprocess = false;
        }
        else {
            incumbent = dijkstra->getIncumbent();
            preprocessingCritical and res_id == RES_CRITICAL ? pruneCritical() : pruning();
            if (Parameters::getVerbosity() >= 3) {
                std::cout << "Incumbent: " << incumbent << std::endl;
                std::cout << "--------" << std::endl;
            }
            dijkstra->resetAlgorithm(0);
            round++;
        }
    }
    else preprocess = false;
    collector.stopGlobalTime();
    collector.increment("iterations", 1);
    collectData();
    return preprocess;
}
Referenced by solve().
resetAlgorithm()
void Preprocessing::resetAlgorithm (int reset_level) override virtual
Implements Algorithm.
Definition at line 86 of file preprocessing.cpp.
{
    problem->resetBoundLabels();
    problem->resetActiveNodes();
    setStatus(ALGO_READY);
}
Referenced by PWAcyclic::resetAlgorithm().
getSplit()
double Preprocessing::getSplit ()
Definition at line 93 of file preprocessing.cpp.
{
    double fw_cost = 0, bw_cost = 0;
    BoundLabels* bound_labels = problem->getBoundLabels();
    if(bound_labels->getLabel(RES_COST, true, problem->getOrigin())->getObjective() == UNKNOWN)
        return 0.5;
    for (int node = 0; node < problem->getNumNodes(); node++) {
        if(not problem->isActiveNode(node))
            continue;
        fw_cost += bound_labels->getLabel(RES_COST, false, node)->getObjective();
        bw_cost += bound_labels->getLabel(RES_COST, true, node)->getObjective();
    }
    if(fw_cost > bw_cost)
        return std::min(1.0, (0.5 * fw_cost / bw_cost));
    else
        return 1 - std::min(1.0, (0.5 * bw_cost / fw_cost));
}
Referenced by PWAcyclic::preprocessing().
pruning()
void Preprocessing::pruning ()
Pruning management
Definition at line 117 of file preprocessing.cpp.
{
    problem->pruneUnreachableNodes(dijkstra->getVisited());
    if(Parameters::getVerbosity() >= 3)
        std::cout<<"Active nodes count after pruning " << problem->countActiveNodes()  << std::endl;
}
Referenced by solveRound().
pruneCritical()
void Preprocessing::pruneCritical ()
Definition at line 124 of file preprocessing.cpp.
{
    criticalActive |= dijkstra->getVisited();
    if(round > 0)
        problem->pruneUnreachableNodes(criticalActive);
    if(Parameters::getVerbosity() >= 3)
        std::cout<<"Active nodes count after pruning: " << problem->countActiveNodes()  << std::endl;
}
Referenced by solveRound().
initDataCollection()
void Preprocessing::initDataCollection ()
Data collection management
Definition at line 134 of file preprocessing.cpp.
{
    collector.setCollectionName("Preprocessing");
    collector.collect("executionID", executionID);
    if(not Parameters::isCollecting())
        return;
    name = "Preprocessing";
    algo_type = "preprocess";
    collector.collect("algo_name", name);
    collector.collect("algo_type", algo_type);
    collector.collect("bidirectional", true);
    collector.init("active_nodes", problem->countActiveNodes());
    collector.setHeader();
}
Referenced by Preprocessing().
collectData()
void Preprocessing::collectData ()
Definition at line 152 of file preprocessing.cpp.
{
    collector.collect("lb", lower_bound); //update lb too
    collector.collect("ub", incumbent);
    collector.collect("algo_status", algo_status);
    collector.collect("active_nodes", problem->countActiveNodes());
    collector.saveRecord();
}
Referenced by solveRound().
Member Data Documentation
round
int Preprocessing::round protected
Definition at line 34 of file preprocessing.h.
Referenced by Preprocessing(), pruneCritical(), and solveRound().
preprocessingCritical
bool Preprocessing::preprocessingCritical protected
Definition at line 36 of file preprocessing.h.
Referenced by Preprocessing(), and solveRound().
criticalActive
Bitset Preprocessing::criticalActive protected
Definition at line 37 of file preprocessing.h.
Referenced by Preprocessing(), and pruneCritical().
dijkstra
Dijkstra* Preprocessing::dijkstra protected
Definition at line 39 of file preprocessing.h.
Referenced by Preprocessing(), pruneCritical(), pruning(), solveRound(), and ~Preprocessing().
The documentation for this class was generated from the following files:
preprocessing.h
preprocessing.cpp