PathWyse: BoundLabels Struct Reference
BoundLabels Struct Reference
#include <bound_data.h>
Public Member Functions
BoundLabels (int n_res, int n_nodes)
~BoundLabels ()=default
void initData ()
void resetData ()
Label * getLabel (int res_id, bool direction, int node)
std::vector< Label > * getCostLabels (int direction)
std::vector< Label > * getConsumptionLabels (int res_id, int direction)
Private Attributes
int n_res
int n_nodes
std::vector< Label > fw_cost
std::vector< Label > bw_cost
std::vector< std::vector< Label > > fw_consumption
std::vector< std::vector< Label > > bw_consumption
Detailed Description
Definition at line 6 of file bound_data.h.
Constructor & Destructor Documentation
BoundLabels()
BoundLabels::BoundLabels (int n_res, int n_nodes) inline
Bound Labels management
Definition at line 11 of file bound_data.h.
{
        this->n_res = n_res;
        this->n_nodes = n_nodes;
        initData();
    }
~BoundLabels()
BoundLabels::~BoundLabels () default
Member Function Documentation
initData()
void BoundLabels::initData () inline
Definition at line 18 of file bound_data.h.
                   {
        fw_cost.resize(n_nodes, Label());
        bw_cost.resize(n_nodes, Label());
        fw_consumption.resize(n_res, std::vector<Label>(n_nodes, Label()));
        bw_consumption.resize(n_res, std::vector<Label>(n_nodes, Label()));
    }
Referenced by BoundLabels(), and resetData().
resetData()
void BoundLabels::resetData () inline
Definition at line 25 of file bound_data.h.
                    {
        fw_cost.clear();
        bw_cost.clear();
        fw_consumption.clear();
        bw_consumption.clear();
        initData();
    }
getLabel()
Label * BoundLabels::getLabel (int res_id, bool direction, int node) inline
Definition at line 34 of file bound_data.h.
{
        if(res_id == RES_COST) {
            auto &cost = direction ? fw_cost : bw_cost;
            return & cost[node];
        }
        else {
            auto &consumption = direction ? fw_consumption: bw_consumption;
            return & consumption[res_id][node];
        }
    }
Referenced by Dijkstra::checkFeasibility(), LMacyclic::earlyUpdate(), Preprocessing::getSplit(), LMacyclic::initLM(), LMacyclic::insert(), LMacyclic::join(), and Dijkstra::joinCompletion().
getCostLabels()
std::vector< Label > * BoundLabels::getCostLabels (int direction) inline
Definition at line 45 of file bound_data.h.
{return direction? & fw_cost: & bw_cost;}
Referenced by Dijkstra::initAlgorithm().
getConsumptionLabels()
std::vector< Label > * BoundLabels::getConsumptionLabels (int res_id, int direction) inline
Definition at line 46 of file bound_data.h.
{return direction? & fw_consumption[res_id]: & bw_consumption[res_id];}
Referenced by Dijkstra::initAlgorithm().
Member Data Documentation
n_res
int BoundLabels::n_res private
Definition at line 50 of file bound_data.h.
Referenced by BoundLabels(), and initData().
n_nodes
int BoundLabels::n_nodes private
Definition at line 51 of file bound_data.h.
Referenced by BoundLabels(), and initData().
fw_cost
std::vector<Label> BoundLabels::fw_cost private
Definition at line 52 of file bound_data.h.
Referenced by getCostLabels(), getLabel(), initData(), and resetData().
bw_cost
std::vector<Label> BoundLabels::bw_cost private
Definition at line 52 of file bound_data.h.
Referenced by getCostLabels(), getLabel(), initData(), and resetData().
fw_consumption
std::vector<std::vector<Label> > BoundLabels::fw_consumption private
Definition at line 53 of file bound_data.h.
Referenced by getConsumptionLabels(), getLabel(), initData(), and resetData().
bw_consumption
std::vector<std::vector<Label> > BoundLabels::bw_consumption private
Definition at line 53 of file bound_data.h.
Referenced by getConsumptionLabels(), getLabel(), initData(), and resetData().
The documentation for this struct was generated from the following file:
bound_data.h