PathWyse: Graph Class Reference
Graph Class Reference
#include <graph.h>
Public Member Functions
Graph ()=default
~Graph ()=default
void initGraph (bool compress_data, int n_nodes, bool complete)
void initCoord ()
void setxs (std::vector< int > x)
void setys (std::vector< int > y)
void setxy (int i, int xval, int yval)
std::pair< int, int > getCoordinates (int node)
int getCoordDistance (int i, int j)
double getEuclideanDistance (double x1, double x2, double y1, double y2)
double getHaversineDistance (double x1, double x2, double y1, double y2)
double getEquirectangularDistance (double x1, double x2, double y1, double y2)
void setArc (int i, int j)
bool areNeighbors (int i, int j, bool direction)
std::vector< int > & getNeighbors (int node, bool direction)
bool isActiveNode (int i)
void pruneActiveNode (int i)
void pruneUnreachableNodes (Bitset &reachable)
int countActiveNodes ()
void activateNode (int i)
void resetActiveNodes ()
double toRadians (double degree)
Private Attributes
int n_nodes
std::vector< int > x
std::vector< int > y
Bitset active_nodes
bool complete
bool compress_data
std::vector< Bitset > arcs
std::vector< std::map< int, bool > > arcs_map
std::vector< std::vector< int > > forward_neighbors
std::vector< std::vector< int > > backward_neighbors
Detailed Description
Definition at line 14 of file graph.h.
Constructor & Destructor Documentation
Graph()
Graph::Graph () default
Graph management
~Graph()
Graph::~Graph () default
Member Function Documentation
initGraph()
void Graph::initGraph (bool compress_data, int n_nodes, bool complete)
Graph management
Definition at line 9 of file graph.cpp.
{
    this->compress_data = compress_data;
    this->n_nodes = n_nodes;
    this->complete = complete;
    if(not complete) {
        if(compress_data)
            arcs_map.resize(n_nodes, std::map<int, bool>());
        else
            arcs.resize(n_nodes, Bitset(n_nodes));
    }
    forward_neighbors.resize(n_nodes, std::vector<int>());
    backward_neighbors.resize(n_nodes, std::vector<int>());
    active_nodes = Bitset(n_nodes);
    active_nodes.set();
}
Referenced by Problem::initProblem().
initCoord()
void Graph::initCoord () inline
Coordinates and distances management
Definition at line 27 of file graph.h.
{x.resize(n_nodes); y.resize(n_nodes);}
Referenced by Problem::readProblem(), and Problem::readSparseProblem().
setxs()
void Graph::setxs (std::vector< int > x) inline
Definition at line 28 of file graph.h.
{this->x = x;}
setys()
void Graph::setys (std::vector< int > y) inline
Definition at line 29 of file graph.h.
{this->y = y;}
setxy()
void Graph::setxy (int i, int xval, int yval) inline
Definition at line 30 of file graph.h.
{x[i] = xval; y[i] = yval;}
Referenced by Problem::readProblem(), and Problem::readSparseProblem().
getCoordinates()
std::pair< int, int > Graph::getCoordinates (int node) inline
Definition at line 31 of file graph.h.
{return std::make_pair(x[node], y[node]);}
getCoordDistance()
int Graph::getCoordDistance (int i, int j)
Coordinates and distances management
Definition at line 28 of file graph.cpp.
{
    const float s = Parameters::getCoordScaling();
    const double xi = x[i]*s, yi = y[i]*s;
    const double xj = x[j]*s, yj = y[j]*s;
    double distance = 0;
    switch(Parameters::getCoordDistanceType()) {
        case DIST_EUCLIDEAN:
            distance = getEuclideanDistance(xi, xj, yi, yj);
            break;
        case DIST_HAVERSINE:
            distance = getHaversineDistance(xi, xj, yi, yj);
            break;
        case DIST_EQUIRECTANGULAR:
            distance = getEquirectangularDistance(xi, xj, yi, yj);
            break;
        default:
            break;
    }
    return static_cast<int>(floor(distance*Parameters::getCoordDistanceScaling()));
}
Referenced by Problem::getCoordDistance().
getEuclideanDistance()
double Graph::getEuclideanDistance (double x1, double x2, double y1, double y2)
Definition at line 53 of file graph.cpp.
{
    return sqrt(pow(xi - xj, 2) + pow(yi - yj, 2));
}
Referenced by getCoordDistance().
getHaversineDistance()
double Graph::getHaversineDistance (double x1, double x2, double y1, double y2)
Definition at line 57 of file graph.cpp.
{
    const double dLon = toRadians(xj - xi);
    const double dLat = toRadians(yj - yi);
    const double a = sin(dLat / 2) * sin(dLat / 2) +
               cos(toRadians(yi)) * cos(toRadians(yj)) *
               sin(dLon / 2) * sin(dLon / 2);
    const double c = 2 * atan2(sqrt(a), sqrt(1 - a));
    return EARTH_RADIUS * c;
}
Referenced by getCoordDistance().
getEquirectangularDistance()
double Graph::getEquirectangularDistance (double x1, double x2, double y1, double y2)
Definition at line 70 of file graph.cpp.
{
    const double dLon = toRadians(xj - xi) * cos(toRadians(yi + yj)/2);
    const double dLat = toRadians(yj - yi);
    return EARTH_RADIUS * sqrt(dLon * dLon + dLat * dLat);
}
Referenced by getCoordDistance().
setArc()
void Graph::setArc (int i, int j)
Arc management
Definition at line 78 of file graph.cpp.
{
    if(i == j) return;
    if(not complete){
        if(compress_data)
            arcs_map[i].insert(std::make_pair(j, true));
        else
            arcs[i].set(j);
    }
    forward_neighbors[i].push_back(j);
    backward_neighbors[j].push_back(i);
}
Referenced by Problem::readProblem(), and Problem::readSparseProblem().
areNeighbors()
bool Graph::areNeighbors (int i, int j, bool direction)
Definition at line 92 of file graph.cpp.
{
    if(i == j)
        return false;
    if(complete)
        return true;
    if(not direction)
        std::swap(i,j);
    return compress_data ? arcs_map[i].count(j) : arcs[i].get(j);
}
Referenced by Problem::areNeighbors().
getNeighbors()
std::vector< int > & Graph::getNeighbors (int node, bool direction) inline
Definition at line 42 of file graph.h.
{return direction ? forward_neighbors[node] : backward_neighbors[node];}
Referenced by Problem::getNeighbors(), and Problem::scaleAllData().
isActiveNode()
bool Graph::isActiveNode (int i) inline
Active nodes management
Definition at line 46 of file graph.h.
{return active_nodes.get(i);}
Referenced by Problem::isActiveNode().
pruneActiveNode()
void Graph::pruneActiveNode (int i) inline
Definition at line 47 of file graph.h.
{active_nodes.set(i, false);}
Referenced by Problem::pruneActiveNode().
pruneUnreachableNodes()
void Graph::pruneUnreachableNodes (Bitset & reachable) inline
Definition at line 48 of file graph.h.
{active_nodes &= reachable;}
Referenced by Problem::pruneUnreachableNodes().
countActiveNodes()
int Graph::countActiveNodes () inline
Definition at line 49 of file graph.h.
{return active_nodes.count();}
Referenced by Problem::countActiveNodes().
activateNode()
void Graph::activateNode (int i) inline
Definition at line 50 of file graph.h.
{active_nodes.set(i);}
Referenced by Problem::activateNode().
resetActiveNodes()
void Graph::resetActiveNodes () inline
Definition at line 51 of file graph.h.
{active_nodes.set();}
Referenced by Problem::resetActiveNodes().
toRadians()
double Graph::toRadians (double degree) inline
Utilities
Definition at line 54 of file graph.h.
{return degree * (M_PI / 180.0);}
Referenced by getEquirectangularDistance(), and getHaversineDistance().
Member Data Documentation
n_nodes
int Graph::n_nodes private
Definition at line 58 of file graph.h.
Referenced by initCoord(), and initGraph().
x
std::vector<int> Graph::x private
Definition at line 59 of file graph.h.
Referenced by getCoordDistance(), getCoordinates(), initCoord(), setxs(), and setxy().
y
std::vector<int> Graph::y private
Definition at line 59 of file graph.h.
Referenced by getCoordDistance(), getCoordinates(), initCoord(), setxy(), and setys().
active_nodes
Bitset Graph::active_nodes private
Definition at line 60 of file graph.h.
Referenced by activateNode(), countActiveNodes(), initGraph(), isActiveNode(), pruneActiveNode(), pruneUnreachableNodes(), and resetActiveNodes().
complete
bool Graph::complete private
Definition at line 62 of file graph.h.
Referenced by areNeighbors(), initGraph(), and setArc().
compress_data
bool Graph::compress_data private
Definition at line 63 of file graph.h.
Referenced by areNeighbors(), initGraph(), and setArc().
arcs
std::vector<Bitset> Graph::arcs private
Definition at line 64 of file graph.h.
Referenced by areNeighbors(), initGraph(), and setArc().
arcs_map
std::vector<std::map<int, bool> > Graph::arcs_map private
Definition at line 65 of file graph.h.
Referenced by areNeighbors(), initGraph(), and setArc().
forward_neighbors
std::vector<std::vector<int> > Graph::forward_neighbors private
Definition at line 67 of file graph.h.
Referenced by getNeighbors(), initGraph(), and setArc().
backward_neighbors
std::vector<std::vector<int> > Graph::backward_neighbors private
Definition at line 67 of file graph.h.
Referenced by getNeighbors(), initGraph(), and setArc().
The documentation for this class was generated from the following files:
graph.h
graph.cpp