PathWyse: Problem Class Reference
Problem Class Reference
#include <problem.h>
Public Member Functions
Problem ()
~Problem ()
void initProblem ()
void setName (std::string name)
std::string getName ()
int getStatus ()
void setStatus (int status)
void printStatus ()
int getNumNodes ()
void setOrigin (int origin)
int getOrigin ()
void setDestination (int destination)
int getDestination ()
bool isGraphCyclic ()
void setGraphCycles (bool cycles)
bool isDataCompressed ()
int getCoordDistance (int i, int j)
bool areNeighbors (int i, int j, bool direction)
std::vector< int > & getNeighbors (int node, bool direction)
bool isActiveNode (int i)
int countActiveNodes ()
void activateNode (int i)
void pruneActiveNode (int i)
void pruneUnreachableNodes (Bitset &reachable)
void resetActiveNodes ()
void initObjective (Resource *objective=nullptr)
int addResource (int type)
void createResources (std::vector< int > &resources_type)
void setRes (Resource *res)
void setRes (int position, Resource *res)
void setResources (std::vector< Resource * > resources)
void setArcConsumption (int i, int j, std::vector< int > consumption)
void setNodeConsumption (int id, std::vector< int > consumption)
int getNumRes ()
Resource * getObj ()
Resource * getRes (int position)
std::vector< Resource * > & getResources ()
void initBoundLabels ()
BoundLabels * getBoundLabels ()
void resetBoundLabels ()
void scaleObjective (float scaling)
void scaleResource (int id, float scaling)
void scaleAllData (float scaling)
virtual void readProblem (std::string file_name)
void readSparseProblem (std::string file_name)
void getTokens (std::string &line, std::vector< std::string > &tokens)
bool readNextLine (std::ifstream &f, std::string &line, std::vector< std::string > &tokens, std::string &key)
void printProblem ()
void initDataCollection ()
void collectData ()
Protected Attributes
std::string name
int problem_status
Graph network
bool directed
bool complete
bool cycles
bool compress_data
int n_nodes
int origin
int destination
int n_arcs
int n_res
Resource * objective
std::vector< Resource * > resources
BoundLabels * bound_labels
DataCollector collector
Detailed Description
Definition at line 17 of file problem.h.
Constructor & Destructor Documentation
Problem()
Problem::Problem ()
Problem Management
Definition at line 8 of file problem.cpp.
                 {
    name = "undefined";
    n_nodes = 0;
    origin = 0;
    destination = 0;
    n_res = 0;
    cycles = false;
    complete = false;
    objective = nullptr;
    bound_labels = nullptr;
    setStatus(PROBLEM_INDETERMINATE);
}
~Problem()
Problem::~Problem ()
Definition at line 21 of file problem.cpp.
                  {
    delete objective;
    delete bound_labels;
    for(auto& r: resources)
        delete r;
}
Member Function Documentation
initProblem()
void Problem::initProblem ()
Definition at line 29 of file problem.cpp.
{
    //Use Data Compression for sparse data
    compress_data = not complete and n_nodes > Parameters::getCompressionThreshold();
    //Duplicate origin node
    if(origin == destination)
        destination = n_nodes++;
    //Initialize Network
    network.initGraph(compress_data, n_nodes, complete);
    //Initialize Objective data structures
    initObjective();
    //Initialize Data Collection
    initDataCollection();
}
Referenced by readProblem(), and readSparseProblem().
setName()
void Problem::setName (std::string name) inline
Definition at line 30 of file problem.h.
{this->name = name;}
getName()
std::string Problem::getName () inline
Definition at line 31 of file problem.h.
{return name;}
getStatus()
int Problem::getStatus () inline
Definition at line 34 of file problem.h.
{return problem_status;}
Referenced by Dijkstra::checkFeasibility(), PWAcyclic::preprocessing(), and Preprocessing::solveRound().
setStatus()
void Problem::setStatus (int status) inline
Definition at line 35 of file problem.h.
{problem_status = status;}
Referenced by Dijkstra::checkFeasibility(), PWDefault::checkTermination(), PWDefault::managePaths(), and Problem().
printStatus()
void Problem::printStatus ()
Definition at line 47 of file problem.cpp.
{
    std::string status;
    switch(problem_status){
        case PROBLEM_INDETERMINATE:
            status = "Indeterminate";
            break;
        case PROBLEM_INFEASIBLE:
            status = "Infeasible";
            break;
        case PROBLEM_FEASIBLE:
            status = "Feasible";
            break;
        default:
            break;
    }
    std::cout << "Problem Status: " << status <<  std::endl;
}
Referenced by Solver::printStatus().
getNumNodes()
int Problem::getNumNodes () inline
Definition at line 39 of file problem.h.
{return n_nodes;}
Referenced by PWDefault::buildNG(), Dijkstra::Dijkstra(), PWDefault::DssrRestricted(), PWDefault::DssrStandard(), Solver::getNumberOfNodes(), Preprocessing::getSplit(), PWDefault::initAlgorithm(), LMacyclic::initLM(), LMDefault::initLM(), PWDefault::NgRestricted(), Preprocessing::Preprocessing(), Solver::printNodeCosts(), printProblem(), and LMacyclic::resetLM().
setOrigin()
void Problem::setOrigin (int origin) inline
Definition at line 42 of file problem.h.
{ this->origin = origin;}
getOrigin()
int Problem::getOrigin () inline
Definition at line 43 of file problem.h.
{return origin;}
Referenced by Algorithm::buildPath(), LMDefault::classicJoin(), Preprocessing::getSplit(), Dijkstra::initAlgorithm(), LMacyclic::initLM(), LMDefault::initLM(), LMDefault::insert(), LMDefault::naiveJoin(), LMDefault::orderedJoin(), LMDefault::setODLabel(), and Preprocessing::solveRound().
setDestination()
void Problem::setDestination (int destination) inline
Definition at line 44 of file problem.h.
{ this->destination = destination;}
getDestination()
int Problem::getDestination () inline
Definition at line 45 of file problem.h.
{return destination;}
Referenced by Algorithm::buildPath(), LMDefault::classicJoin(), Dijkstra::initAlgorithm(), LMacyclic::initLM(), LMDefault::initLM(), LMDefault::insert(), LMDefault::naiveJoin(), LMDefault::orderedJoin(), LMDefault::setODLabel(), and Preprocessing::solveRound().
isGraphCyclic()
bool Problem::isGraphCyclic () inline
Definition at line 48 of file problem.h.
{return cycles;}
Referenced by LMDefault::insert(), LMDefault::readConfiguration(), and PWAcyclic::solve().
setGraphCycles()
void Problem::setGraphCycles (bool cycles) inline
Definition at line 49 of file problem.h.
{this->cycles = cycles;}
isDataCompressed()
bool Problem::isDataCompressed () inline
Definition at line 52 of file problem.h.
{return compress_data;}
getCoordDistance()
int Problem::getCoordDistance (int i, int j) inline
Graph management
Definition at line 56 of file problem.h.
{return network.getCoordDistance(i, j);}
Referenced by Dijkstra::solve().
areNeighbors()
bool Problem::areNeighbors (int i, int j, bool direction) inline
Definition at line 59 of file problem.h.
{return network.areNeighbors(i, j, direction);}
Referenced by PWDefault::buildNG(), LMDefault::classicJoin(), LMDefault::naiveJoin(), and LMDefault::orderedJoin().
getNeighbors()
std::vector< int > & Problem::getNeighbors (int node, bool direction) inline
Definition at line 60 of file problem.h.
{return network.getNeighbors(node, direction);}
Referenced by PWAcyclic::extend(), PWDefault::extend(), Dijkstra::solve(), and LMDefault::updateUnreachables().
isActiveNode()
bool Problem::isActiveNode (int i) inline
Definition at line 63 of file problem.h.
{return network.isActiveNode(i);}
Referenced by PWAcyclic::extend(), Preprocessing::getSplit(), and Dijkstra::solve().
countActiveNodes()
int Problem::countActiveNodes () inline
Definition at line 64 of file problem.h.
{return network.countActiveNodes();}
Referenced by Preprocessing::collectData(), Preprocessing::initDataCollection(), Preprocessing::pruneCritical(), and Preprocessing::pruning().
activateNode()
void Problem::activateNode (int i) inline
Definition at line 66 of file problem.h.
{network.activateNode(i);}
pruneActiveNode()
void Problem::pruneActiveNode (int i) inline
Definition at line 68 of file problem.h.
{network.pruneActiveNode(i);}
pruneUnreachableNodes()
void Problem::pruneUnreachableNodes (Bitset & reachable) inline
Definition at line 69 of file problem.h.
{network.pruneUnreachableNodes(reachable);}
Referenced by Preprocessing::pruneCritical(), and Preprocessing::pruning().
resetActiveNodes()
void Problem::resetActiveNodes () inline
Definition at line 71 of file problem.h.
{network.resetActiveNodes();}
Referenced by Preprocessing::resetAlgorithm().
initObjective()
void Problem::initObjective (Resource * objective = nullptr)
Objective and Resource management
Definition at line 69 of file problem.cpp.
{
    //If a custom objective is not defined, use default objective
    if(not objective)
        objective = new DefaultCost();
    this->objective = objective;
    //Initialize data structures
    this->objective->initData(compress_data, n_nodes);
}
Referenced by initProblem().
addResource()
int Problem::addResource (int type)
Definition at line 80 of file problem.cpp.
{
    Resource* res;
    int index;
    switch(type){
        case RES_CAPACITY:
            res = new Capacity();
        break;
        case RES_TIME:
            res = new Time();
        break;
        case RES_TIMEWINDOWS:
            res = new TimeWindow();
        break;
        case RES_NODELIM:
            res = new NodeLim();
        break;
        default:
            std::cout << "Inserted type does not correspond to any default resource" << std::endl;
        break;
    }
    resources.push_back(res);
    res->initData(compress_data, n_nodes);
    return index;
}
Referenced by createResources(), readProblem(), and readSparseProblem().
createResources()
void Problem::createResources (std::vector< int > & resources_type)
Definition at line 108 of file problem.cpp.
{
    for(auto rt: resources_type)
        addResource(rt);
}
setRes() [1/2]
void Problem::setRes (Resource * res) inline
Definition at line 80 of file problem.h.
{resources.push_back(res);}
setRes() [2/2]
void Problem::setRes (int position, Resource * res) inline
Definition at line 81 of file problem.h.
{resources[position] = res;}
setResources()
void Problem::setResources (std::vector< Resource * > resources) inline
Definition at line 82 of file problem.h.
{this->resources = resources;}
setArcConsumption()
void Problem::setArcConsumption (int i, int j, std::vector< int > consumption)
Definition at line 113 of file problem.cpp.
{
    for(int r = 0; r < resources.size(); r++)
        resources[r]->setArcCost(i, j, consumption[r]);
}
setNodeConsumption()
void Problem::setNodeConsumption (int id, std::vector< int > consumption)
Definition at line 118 of file problem.cpp.
{
    for(int r = 0; r < resources.size(); r++)
        if(consumption[r] >= 0)
            resources[r]->setNodeCost(id, consumption[r]);
}
getNumRes()
int Problem::getNumRes () inline
Definition at line 89 of file problem.h.
{return resources.size();}
Referenced by LMacyclic::buildTour(), LMDefault::buildTour(), Dijkstra::buildTour(), Dijkstra::checkFeasibility(), Algorithm::collectSolution(), LMDefault::extendLabel(), Algorithm::initDataCollection(), LMacyclic::initLM(), LMDefault::initLM(), LMDefault::isJoinFeasible(), and LMDefault::printStepConsumption().
getObj()
Resource * Problem::getObj () inline
Definition at line 90 of file problem.h.
{return objective;}
Referenced by PWDefault::buildNG(), Algorithm::buildPath(), LMacyclic::buildTour(), LMDefault::buildTour(), Dijkstra::buildTour(), LMDefault::classicJoin(), collectData(), Dijkstra::Dijkstra(), LMDefault::extendLabel(), LMacyclic::initLM(), LMDefault::initLM(), LMDefault::naiveJoin(), LMDefault::orderedJoin(), Solver::printNodeCosts(), Solver::setInitCost(), Solver::setNodeCost(), and Solver::setNodeCost().
getRes()
Resource * Problem::getRes (int position) inline
Definition at line 91 of file problem.h.
{return resources[position];}
Referenced by collectData(), Dijkstra::Dijkstra(), LMacyclic::initLM(), and LMDefault::printStepConsumption().
getResources()
std::vector< Resource * > & Problem::getResources () inline
Definition at line 92 of file problem.h.
{return resources;}
Referenced by LMacyclic::buildTour(), LMDefault::buildTour(), Dijkstra::buildTour(), LMDefault::extendLabel(), LMDefault::initLM(), LMDefault::isCriticalExtensionFeasible(), LMDefault::isExtensionFeasible(), and LMDefault::isJoinFeasible().
initBoundLabels()
void Problem::initBoundLabels () inline
Completion Labels management
Definition at line 96 of file problem.h.
{bound_labels = new BoundLabels(n_res, n_nodes);}
Referenced by PWAcyclic::PWAcyclic(), and resetBoundLabels().
getBoundLabels()
BoundLabels * Problem::getBoundLabels () inline
Definition at line 97 of file problem.h.
{return bound_labels;}
Referenced by Preprocessing::getSplit(), Dijkstra::initAlgorithm(), and LMacyclic::LMacyclic().
resetBoundLabels()
void Problem::resetBoundLabels () inline
Definition at line 98 of file problem.h.
{delete bound_labels; initBoundLabels();}
Referenced by Preprocessing::resetAlgorithm().
scaleObjective()
void Problem::scaleObjective (float scaling)
Definition at line 124 of file problem.cpp.
{
    objective->scaleResource(scaling);
}
Referenced by Solver::revertScaleData(), and Solver::scaleData().
scaleResource()
void Problem::scaleResource (int id, float scaling)
Definition at line 128 of file problem.cpp.
{
    resources[id]->scaleResource(scaling);
}
Referenced by Solver::scaleData().
scaleAllData()
void Problem::scaleAllData (float scaling)
Definition at line 132 of file problem.cpp.
{
    objective->multiplyInitValue(scaling);
    objective->multiplyUB(scaling);
    objective->multiplyLB(scaling);
    for(auto r: resources){
        r->multiplyInitValue(scaling);
        r->multiplyUB(scaling);
        r->multiplyLB(scaling);
    }
    for(int i = 0; i < n_nodes; i++) {
        objective->multiplyNodeCost(i, scaling);
        objective->multiplyNodeBound(i, scaling);
        for(auto r: resources){
            r->multiplyNodeCost(i, scaling);
            r->multiplyNodeBound(i, scaling);
        }
        auto& neighbors = network.getNeighbors(i, true);
        for(auto j: neighbors) {
            objective->multiplyArcCost(i, j, scaling);
            for(auto r: resources)
                r->multiplyArcCost(i, j, scaling);
        }
    }
}
Referenced by Solver::revertScaleData(), and Solver::scaleData().
readProblem()
void Problem::readProblem (std::string file_name) virtual
Read from instance file
Definition at line 380 of file problem.cpp.
{
    std::ifstream f;
    std::string line, key, label, separator, res_name, res_type;
    std::vector<std::string> tokens;
    int res_id, i, j, cluster_id;
    bool symmetric = false, use_depot = false;
    int lb, ub, cost, consumption;
    directed = true;
    if(Parameters::getVerbosity() >= 0)
        std::cout<<"Reading problem data: "<<file_name<<std::endl;
    //If present, override origin and destination with console input
    if(Parameters::getOrigin() != -1)
        this->origin = Parameters::getOrigin();
    if(Parameters::getDestination() != -1)
        this->destination = Parameters::getDestination();
    //Read from file
    f.open(file_name.c_str());
    while(readNextLine(f, line, tokens, key)) {
        //Read initialization data
        if (key == "NAME") this->name = tokens[2];
        else if (key == "SIZE") this->n_nodes = std::stoi(tokens[2]);
        //else if (key == "CLUSTERS") this->n_clusters = std::stoi(tokens[2]);
        else if (key == "DIRECTED") directed = std::stoi(tokens[2]);
        else if (key == "CYCLIC") this->cycles = std::stoi(tokens[2]);
        else if (key == "SYMMETRIC") symmetric = std::stoi(tokens[2]);
        else if (key == "COMPLETE") {
            this->complete = std::stoi(tokens[2]);
            collector.collect("complete", complete);
        }
        else if (key == "RESOURCES") this->n_res = std::stoi(tokens[2]);
        else if (key == "ORIGIN") {
            if(Parameters::getOrigin() == -1)
                this->origin = std::stoi(tokens[2]);
        }
        else if (key == "DESTINATION") {
            if(Parameters::getDestination() == -1)
                this->destination = std::stoi(tokens[2]);
        }
        else if (key == "RES_TYPE") {
            //Duplicate origin node if necessary
            if (origin == destination)
                use_depot = true;
            //Initialize problem
            initProblem();
            readNextLine(f, line, tokens, key);
            while(key != "END") {
                //Initialize resource objects
                res_type = tokens[1];
                if (res_type == "CAP") addResource(RES_CAPACITY);
                else if (res_type == "TIME") addResource(RES_TIME);
                else if (res_type == "TW") addResource(RES_TIMEWINDOWS);
                else if (res_type == "NODELIM") addResource(RES_NODELIM);
                readNextLine(f, line, tokens, key);
            }
        }
        else if (key == "RES_BOUND") {
            //Read lower bound and upperbound for each resource
            readNextLine(f, line, tokens, key);
            while (key != "END") {
                res_id = std::stoi(tokens[0]);
                lb = std::stoi(tokens[1]);
                ub = std::stoi(tokens[2]);
                if(res_id == 0 and Parameters::getCriticalUB() != -1)
                    ub = Parameters::getCriticalUB();
                resources[res_id]->setBounds(lb, ub);
                readNextLine(f, line, tokens, key);
            }
        }
        else if (key == "RES_NODE_BOUND") {
            //For each node i, add lower and upper bound for a given resource
            readNextLine(f, line, tokens, key);
            while (key != "END") {
                res_id = std::stoi(tokens[0]);
                i = std::stoi(tokens[1]);
                lb = std::stoi(tokens[2]);
                ub = std::stoi(tokens[3]);
                resources[res_id]->setNodeBound(n_nodes, i, lb, ub);
                readNextLine(f, line, tokens, key);
            }
        }
        else if (key == "EDGE_COST") {
            //For each arc i-j, read a cost
            readNextLine(f, line, tokens, key);
            while (key != "END") {
                i = std::stoi(tokens[0]);
                j = std::stoi(tokens[1]);
                cost = std::stoi(tokens[2]);
                objective->setArcCost(i, j, cost);
                //Add an arc to the network
                network.setArc(i, j);
                n_arcs++;
                if (!directed) {
                    objective->setArcCost(j, i, cost);
                    network.setArc(j, i);
                    n_arcs++;
                }
                if (use_depot and (i == origin or j == origin)) {
                    i == origin ? i = destination : j = destination;
                    objective->setArcCost(i, j, cost);
                    network.setArc(i, j);
                    n_arcs++;
                    if (!directed) {
                        objective->setArcCost(j, i, cost);
                        network.setArc(j, i);
                        n_arcs++;
                    }
                }
                readNextLine(f, line, tokens, key);
            }
        }
        else if (key == "NODE_COST") {
            //For each node i, read a cost
            readNextLine(f, line, tokens, key);
            while (key != "END") {
                i = std::stoi(tokens[0]);
                cost = std::stoi(tokens[1]);
                objective->setNodeCost(i, cost);
                if (use_depot and i == origin)
                    objective->setNodeCost(destination, 0);
                readNextLine(f, line, tokens, key);
            }
        }
        else if(key == "EDGE_CONSUMPTION") {
            //For each arc i-j, read a resource consumption
            readNextLine(f, line, tokens, key);
            while (key != "END") {
                res_id = std::stoi(tokens[0]);
                i = std::stoi(tokens[1]);
                j = std::stoi(tokens[2]);
                consumption = std::stoi(tokens[3]);
                resources[res_id]->setArcCost(i, j, consumption);
                if (!directed)
                    resources[res_id]->setArcCost(j, i, consumption);
                if (use_depot and (i == origin or j == origin)) {
                    i == origin ? i = destination : j = destination;
                    resources[res_id]->setArcCost(i, j, consumption);
                    if (!directed)
                        resources[res_id]->setArcCost(j, i, consumption);
                }
                readNextLine(f, line, tokens, key);
            }
        }
        else if (key == "NODE_CONSUMPTION") {
            //For each node i, read a resource consumption
            readNextLine(f, line, tokens, key);
            while (key != "END") {
                res_id = std::stoi(tokens[0]);
                i = std::stoi(tokens[1]);
                consumption = std::stoi(tokens[2]);
                resources[res_id]->setNodeCost(i, consumption);
                if (use_depot and i == origin)
                    resources[res_id]->setNodeCost(destination, 0);
                readNextLine(f, line, tokens, key);
            }
        }
        else if (key == "COORD") {
            //For each node i, read coordinates (x,y)
            readNextLine(f, line, tokens, key);
            network.initCoord();
            int xval, yval;
            while (key != "END") {
                i = std::stoi(tokens[0]);
                xval = std::stoi(tokens[1]);
                yval = std::stoi(tokens[2]);
                network.setxy(i, xval, yval);
                if(use_depot and i == origin)
                    network.setxy(destination, xval, yval);
                readNextLine(f, line, tokens, key);
            }
        }
    }
    f.close();
    if(Parameters::getVerbosity() >= 0){
        std::cout<<"Reading problem data complete"<<std::endl;
        std::cout<<"--------------------"<<std::endl;
    }
    //Initialize resources
    for(auto r: resources)
        r->init(origin, destination);
    printProblem();
    collectData();
}
Referenced by Solver::readProblem().
readSparseProblem()
void Problem::readSparseProblem (std::string file_name)
Read from instance file
Definition at line 162 of file problem.cpp.
{
    std::ifstream f;
    std::string line, key, label, separator, res_name, res_type, data_type;
    std::vector<std::string> tokens;
    bool symmetric = false, use_depot = false;
    int res_id, i, j, di, dj, xval, yval;
    int lb, ub, cost, consumption;
    directed = true;
    if(Parameters::getVerbosity() >= 3)
        std::cout<<"Reading problem data: "<<file_name<<std::endl;
    //If present, override origin and destination with console input
    if(Parameters::getOrigin() != -1)
        this->origin = Parameters::getOrigin();
    if(Parameters::getDestination() != -1)
        this->destination = Parameters::getDestination();
    //Read from file
    f.open(file_name.c_str());
    while(readNextLine(f, line, tokens, key)) {
        //Read initialization data
        if (key == "NAME") this->name = tokens[2];
        else if (key == "SIZE") this->n_nodes = std::stoi(tokens[2]);
        else if (key == "DIRECTED") directed = std::stoi(tokens[2]);
        else if (key == "CYCLIC") this->cycles = std::stoi(tokens[2]);
        else if (key == "SYMMETRIC") symmetric = std::stoi(tokens[2]);
        else if (key == "COMPLETE") {
            this->complete = std::stoi(tokens[2]);
            collector.collect("complete", complete);
        }
        else if (key == "RESOURCES") this->n_res = std::stoi(tokens[2]);
        else if (key == "ORIGIN") {
            if (Parameters::getOrigin() == -1)
                this->origin = std::stoi(tokens[2]);
        }
        else if (key == "DESTINATION") {
            if (Parameters::getDestination() == -1)
                this->destination = std::stoi(tokens[2]);
        }
        else if (key == "RES_TYPE") {
            //Duplicate origin node if necessary
            if (origin == destination)
                use_depot = true;
            //Initialize problem
            initProblem();
            readNextLine(f, line, tokens, key);
            while (key != "END") {
                //Initialize resource objects
                res_type = tokens[1];
                if (res_type == "CAP") addResource(RES_CAPACITY);
                else if (res_type == "TIME") addResource(RES_TIME);
                else if (res_type == "TW") addResource(RES_TIMEWINDOWS);
                else if (res_type == "NODELIM") addResource(RES_NODELIM);
                readNextLine(f, line, tokens, key);
            }
        }
        else if (key == "RES_BOUND") {
            readNextLine(f, line, tokens, key);
            //Read lower bound and upperbound for each resource
            while (key != "END") {
                res_id = tokens[0].at(1) - '0';
                lb = std::stoi(tokens[1]);
                ub = std::stoi(tokens[2]);
                if (res_id == 0 and Parameters::getCriticalUB() != -1)
                    ub = Parameters::getCriticalUB();
                resources[res_id]->setBounds(lb, ub);
                readNextLine(f, line, tokens, key);
            }
        }
        else if (key == "NODE_DATA") {
            //Read node data: for each node i, read coordinates (x, y), cost and resource consumption
            readNextLine(f, line, tokens, key);
            auto header = tokens;
            if(std::find(header.begin(), header.end(), "x") != header.end())
                network.initCoord();
            readNextLine(f, line, tokens, key);
            while (key != "END") {
                i = std::stoi(tokens[0]);
                for (int index = 1; index < header.size(); index++) {
                    data_type = header[index];
                    if (data_type == "x") {
                        xval = std::stoi(tokens[index++]);
                        yval = std::stoi(tokens[index]);
                        network.setxy(i, xval, yval);
                    }
                    else if (data_type == "COST") {
                        cost = std::stoi(tokens[index]);
                        objective->setNodeCost(i, cost);
                    }
                    else {
                        res_id = data_type.at(1) - '0';
                        consumption = std::stoi(tokens[index]);
                        resources[res_id]->setNodeCost(i, consumption);
                    }
                }
                readNextLine(f, line, tokens, key);
            }
        }
        else if (key == "ARC_DATA") {
            //Read node data: for each arc i-j, read coordinates (x, y), costs and resource consumption
            //Add arcs j-i if the graph is not directed
            //If the origin node is duplicated, add arcs for the destination
            readNextLine(f, line, tokens, key);
            auto header = tokens;
            readNextLine(f, line, tokens, key);
            while (key != "END") {
                i = std::stoi(tokens[0]);
                j = std::stoi(tokens[1]);
                //Add an arc to the network
                network.setArc(i, j);
                n_arcs++;
                if (not directed) {
                    network.setArc(j, i);
                    n_arcs++;
                }
                if (use_depot and (i == origin or j == origin)) {
                    di = i == origin ? destination : i;
                    dj = j == origin ? destination : j;
                    network.setArc(di, dj);
                    n_arcs++;
                    if (not directed) {
                        network.setArc(dj, di);
                        n_arcs++;
                    }
                }
                for (int index = 2; index < header.size(); index++) {
                    data_type = header[index];
                    if (data_type == "COST") {
                        cost = std::stoi(tokens[index]);
                        objective->setArcCost(i, j, cost);
                        if (not directed)
                            objective->setArcCost(j, i, cost);
                        if (use_depot and (i == origin or j == origin)) {
                            objective->setArcCost(di, dj, cost);
                            if (not directed)
                                objective->setArcCost(dj, di, cost);
                        }
                    }
                    else {
                        res_id = data_type.at(1) - '0';
                        consumption = std::stoi(tokens[index]);
                        resources[res_id]->setArcCost(i, j, consumption);
                        if (not directed)
                            resources[res_id]->setArcCost(j, i, consumption);
                        if (use_depot and (i == origin or j == origin)) {
                            resources[res_id]->setArcCost(di, dj, consumption);
                            if (not directed)
                                resources[res_id]->setArcCost(dj, di, consumption);
                        }
                    }
                }
                readNextLine(f, line, tokens, key);
            }
        }
        else if (key == "RES_NODE_BOUND") {
            //For each node i, add lower and upper bound for a given resource
            readNextLine(f, line, tokens, key);
            while (key != "END") {
                res_id = tokens[0].at(1) - '0';
                i = std::stoi(tokens[1]);
                lb = std::stoi(tokens[2]);
                ub = std::stoi(tokens[3]);
                resources[res_id]->setNodeBound(n_nodes, i, lb, ub);
                readNextLine(f, line, tokens, key);
            }
        }
        else if (key == "COORD") {
            //For each node i, read coordinates (x,y)
            readNextLine(f, line, tokens, key);
            network.initCoord();
            int xval, yval;
            while (key != "END") {
                i = std::stoi(tokens[0]);
                xval = std::stoi(tokens[1]);
                yval = std::stoi(tokens[2]);
                network.setxy(i, xval, yval);
                if(use_depot and i == origin)
                    network.setxy(destination, xval, yval);
                readNextLine(f, line, tokens, key);
            }
        }
    }
    f.close();
    if(Parameters::getVerbosity() >= 3)
        std::cout<<"Reading problem data complete"<<std::endl;
    //Initialize resources
    for(auto r: resources)
        r->init(origin, destination);
    printProblem();
    collectData();
}
getTokens()
void Problem::getTokens (std::string & line, std::vector< std::string > & tokens)
Definition at line 604 of file problem.cpp.
{
    tokens.clear();
    std::istringstream iss(line);
    tokens = {std::istream_iterator<std::string>{iss},std::istream_iterator<std::string>{}};
}
Referenced by readNextLine().
readNextLine()
bool Problem::readNextLine (std::ifstream & f, std::string & line, std::vector< std::string > & tokens, std::string & key)
Definition at line 610 of file problem.cpp.
{
    if(getline(f, line)) {
        getTokens(line, tokens);
        key = tokens[0];
        return true;
    }
    return false;
}
Referenced by readProblem(), and readSparseProblem().
printProblem()
void Problem::printProblem ()
Output management
Definition at line 621 of file problem.cpp.
{
    if(Parameters::getVerbosity() < 1)
        return;
    std::cout<< "Problem: " << name << std::endl;
    std::cout<< "Number of resources: " << n_res << std::endl;
    std::cout<< "Number of nodes: " << getNumNodes() << std::endl;
    std::cout<<"Origin: " << this->origin << std::endl;
    std::cout<<"Destination: " << this->destination << std::endl;
    std::cout<<"Upperbounds: ";
    for(auto & r: resources)
        std::cout << r->getUB()<< " ";
    std::cout<<std::endl;
    std::cout << "--------------------" << std::endl;
}
Referenced by readProblem(), and readSparseProblem().
initDataCollection()
void Problem::initDataCollection ()
Data collection
Definition at line 638 of file problem.cpp.
{
    collector = DataCollector("Problem");
    if(not Parameters::isCollecting())
        return;
    collector.init("problem_name", "");
    collector.init("nodes", 0);
    collector.init("arcs", 0);
    collector.init("arcs_per_node", 0.0);
    collector.init("complete", -1);
    collector.init("symmetric", -1);
    collector.init("directed", -1);
    collector.init("cyclic", -1);
    collector.init("nres", 0);
    collector.init("nres_complex", 0);
    collector.init("origin", -1);
    collector.init("destination", -1);
    collector.init("obj_init", 0);
    collector.init("obj_lb", 0);
    collector.init("obj_ub", 0);
}
Referenced by initProblem().
collectData()
void Problem::collectData ()
Definition at line 661 of file problem.cpp.
{
    if(not Parameters::isCollecting())
        return;
    collector.collect("problem_name", name);
    collector.collect("nodes", n_nodes);
    collector.collect("arcs", n_arcs);
    collector.collect("arcs_per_node", (double)n_arcs/n_nodes);
    collector.collect("directed", directed);
    collector.collect("cyclic", cycles);
    collector.collect("nres", n_res);
    collector.collect("origin", origin);
    collector.collect("destination", destination);
    collector.collect("obj_init", getObj()->getInitValue());
    collector.collect("obj_lb", getObj()->getLB());
    collector.collect("obj_ub", getObj()->getUB());
    for(int i = 0; i < resources.size(); i++) {
        auto res = getRes(i);
        std::string tag = "r" + std::to_string(i) + "_";
        collector.init(tag+"init", res->getInitValue());
        collector.init(tag+"lb", res->getLB());
        collector.init(tag+"ub", res->getUB());
    }
    collector.setHeader();
    collector.saveRecord();
    collector.writeData();
}
Referenced by readProblem(), and readSparseProblem().
Member Data Documentation
name
std::string Problem::name protected
Definition at line 121 of file problem.h.
Referenced by collectData(), getName(), printProblem(), Problem(), readProblem(), readSparseProblem(), and setName().
problem_status
int Problem::problem_status protected
Definition at line 122 of file problem.h.
Referenced by getStatus(), printStatus(), and setStatus().
network
Graph Problem::network protected
Definition at line 125 of file problem.h.
Referenced by activateNode(), areNeighbors(), countActiveNodes(), getCoordDistance(), getNeighbors(), initProblem(), isActiveNode(), pruneActiveNode(), pruneUnreachableNodes(), readProblem(), readSparseProblem(), resetActiveNodes(), and scaleAllData().
directed
bool Problem::directed protected
Definition at line 126 of file problem.h.
Referenced by collectData(), readProblem(), and readSparseProblem().
complete
bool Problem::complete protected
Definition at line 127 of file problem.h.
Referenced by initProblem(), Problem(), readProblem(), and readSparseProblem().
cycles
bool Problem::cycles protected
Definition at line 128 of file problem.h.
Referenced by collectData(), isGraphCyclic(), Problem(), readProblem(), readSparseProblem(), and setGraphCycles().
compress_data
bool Problem::compress_data protected
Definition at line 129 of file problem.h.
Referenced by addResource(), initObjective(), initProblem(), and isDataCompressed().
n_nodes
int Problem::n_nodes protected
Definition at line 132 of file problem.h.
Referenced by addResource(), collectData(), getNumNodes(), initBoundLabels(), initObjective(), initProblem(), Problem(), readProblem(), readSparseProblem(), and scaleAllData().
origin
int Problem::origin protected
Definition at line 133 of file problem.h.
Referenced by collectData(), getOrigin(), initProblem(), printProblem(), Problem(), readProblem(), readSparseProblem(), and setOrigin().
destination
int Problem::destination protected
Definition at line 133 of file problem.h.
Referenced by collectData(), getDestination(), initProblem(), printProblem(), Problem(), readProblem(), readSparseProblem(), and setDestination().
n_arcs
int Problem::n_arcs protected
Definition at line 136 of file problem.h.
Referenced by collectData(), readProblem(), and readSparseProblem().
n_res
int Problem::n_res protected
Definition at line 139 of file problem.h.
Referenced by collectData(), initBoundLabels(), printProblem(), Problem(), readProblem(), and readSparseProblem().
objective
Resource* Problem::objective protected
Definition at line 140 of file problem.h.
Referenced by getObj(), initObjective(), Problem(), readProblem(), readSparseProblem(), scaleAllData(), scaleObjective(), and ~Problem().
resources
std::vector<Resource*> Problem::resources protected
Definition at line 141 of file problem.h.
Referenced by addResource(), collectData(), getNumRes(), getRes(), getResources(), printProblem(), readProblem(), readSparseProblem(), scaleAllData(), scaleResource(), setArcConsumption(), setNodeConsumption(), setRes(), setRes(), setResources(), and ~Problem().
bound_labels
BoundLabels* Problem::bound_labels protected
Definition at line 144 of file problem.h.
Referenced by getBoundLabels(), initBoundLabels(), Problem(), resetBoundLabels(), and ~Problem().
collector
DataCollector Problem::collector protected
Definition at line 147 of file problem.h.
Referenced by collectData(), initDataCollection(), readProblem(), and readSparseProblem().
The documentation for this class was generated from the following files:
problem.h
problem.cpp